### PR TITLE
COMP: Fix variable type and syntax errors

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix expected variable type and syntax errors in `ITK_TEST_SET_GET_VALUE`
calls.

Fixes:
```
/Users/builder/externalModules/Filtering/ImageCompare/test/itkTestingComparisonImageFilterTest.cxx:71:21: error:
called object type 'const char [55]' is not a function or function pointer
  TEST_SET_GET_VALUE(differenceThreshold, filter->GetDifferenceThreshold());
  ~~~~~~~~~~~~~~~~~~^
/Users/builder/externalModules/Filtering/ImageCompare/test/itkTestingComparisonImageFilterTest.cxx:75:21:
error: called object type 'const char [55]' is not a function or function pointer
  TEST_SET_GET_VALUE(toleranceRadius, filter->GetToleranceRadius());
  ~~~~~~~~~~~~~~~~~~^
2 errors generated.
```

and
```
/Users/builder/externalModules/Registration/Common/test/itkMattesMutualInformationImageToImageMetricTest.cxx:223:84:
error: expected ';' after static_assert
  ITK_TEST_SET_GET_VALUE(numberOfHistogramBins, metric->GetNumberOfHistogramBins())
                                                                                   ^
                                                                                   ;
```

Raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=7679319

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Issue introduced in #3077.

**Review by thewtex — APPROVED** [review]
:green_heart:

**Review by dzenanz — APPROVED** [review]
