### ISSUE TITLE
Custom module's export generated in wrong folder.

### ISSUE THREAD

**Issue by al-sabr** [InsightSoftwareConsortium/ITK#2325]
Ok the module is now recognized but somehow it doesn't generate the export file which is **itkInternalExport.h**

How ís it possible to make my module generate its own Export file? Do I need to specify it somewhere?

Ohh that's weird the file is generated but in the wrong folder

![image](https://user-images.githubusercontent.com/26530975/108078499-0d7de500-706e-11eb-8711-aba4b4807a65.png)

It should actually be in **Modules/Basic/Internal/itkInternalExport.h**

Why does it find itself in Common when I deactivated the Group\_Common?

**Comment by al-sabr** [comment]
Also how does the **itkExport.h** gets generated because I have also a compilation error telling me that the file is non-existent.

![](https://user-images.githubusercontent.com/26530975/108117399-2c47a000-709d-11eb-9f51-dbccfe776ebc.png)

**Comment by al-sabr** [comment]
It seems that this is the reason why the file gets generated in the wrong folder:

https://github.com/InsightSoftwareConsortium/ITK/blob/c2116d956b17288dfd3bd58aec2fb4cade4324b1/CMake/ITKModuleMacros.cmake#L220

**Comment by dzenanz** [comment]
`ITKCommon` is assumed to always be built. Your rewrite violates that assumption.

**Comment by al-sabr** [comment]
ITKCommon is not compiling because of previous GDSM problem. That's why I have to do this so that it doesn't depend on that whole Common thing.

**Comment by al-sabr** [comment]
This is the error I am talking about... ITKCommon doesn't compile : https://github.com/commontk/CTK/issues/949#issuecomment-777070686

**Comment by jhlegarreta** [comment]
@al-sabr I've been loosely following the threads you posted across many channels, including issues such as this one, posts to the [ITK discourse](https://discourse.itk.org/), [CTK issues in GitHub](https://github.com/commontk/CTK/issues) or the [CMake discourse](https://discourse.cmake.org/), and I think a comment is necessary as a maintainer of the toolkit/long time contributor.

Although I do not have the resources to have a look into the issues, a few general comments apply to the use of the channels and resources:
- Posting the same issue (or its variants) across multiple channels makes more difficult to keep track of it. This applies both to maintainers that might take the time to have a look into the issue, and to other members that might eventually bump into the same problem and be willing to follow the discussion and hints provided.
- [ITK's GitHub issues](https://github.com/InsightSoftwareConsortium/ITK/issues) are not intended to ask questions. Questions should be posted in ITK's [discourse](https://discourse.itk.org/).
- [ITK's GitHub issues](https://github.com/InsightSoftwareConsortium/ITK/issues) have many [templates](https://github.com/InsightSoftwareConsortium/ITK/issues/new/choose) to facilitate building an accurate and detailed report that might allow other individuals reproduce your results or failures. Failing to provide such information limits the insight you may get. And in either case, note that maintainers might not be in a position to reproduce the issue for various reasons.
- You can set up regular builds for your application and have them submitted to [a CDash server](https://open.cdash.org/viewProjects.php) so that the failure reports are visible and can be inspected.
- Bug fixes and enhancements are much appreciated and everybody is [welcome to submit them](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md).

As for ITK's design,
- Note that ITK is being developed since 1999, it has enabled and enables many cutting edge applications across a variety of scientific fields, supports reproducible open scientific research, and is a model as a long lasting community effort in such a context.
- A large number of people have contributed and put their valuable time and efforts into ITK. Many of these individuals are prominent researchers and developers, have a vast experience across various domains, and their design decisions have been grounded on the basis of evidence, reproducibility, knowledge sharing, and overall excellent software development practice.
- Note that a number of large scale and third-party software, both private and public, depend on ITK, and maintain regular (i.e. daily) testing that proves that ITK works as expected under various conditions.

And **especially**, and more generally,
- ITK has a [code of conduct](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CODE_OF_CONDUCT.md) and its [discourse guidelines](https://discourse.itk.org/guidelines) are a necessary read before participating in community discussions.
- Some comments that were made in the context of such posts and their tone are largely unwelcome within this community.
- Many contributors contribute to ITK as a side project on their own time. Their time is valuable, as valuable as one's own time. So be considerate, and think about it when posting failure reports and messages.

So, please keep the discussion civilized and acknowledge the effort of the many individuals that have provided support.

**Comment by al-sabr** [comment]
Let me know if I said something which was out of order. I'll try to be more civilized.

**Comment by dzenanz** [comment]
You are combining libraries in ways not envisioned by their authors, but you are expecting help as if you are using it in a supported way. You want to create a new library by forking CTK? Go ahead, but don't blame ITK that a mutilated version of it is not compiling.

**Comment by al-sabr** [comment]
I thought that ITK is modular and tried to move some stuff out to bypass the compilation error generated by GDSM. I envisioned that it will be easy since there is the documentation but I keep hitting road blocks. And no one explained why GDSM is not compiling even though I went the way you suggested @dzenanz. At some point I might be headed wrong but I definitely appreciate your input since you are there from the beginning.

**Comment by jhlegarreta** [comment]
> Let me know if I said something which was out of order. I'll try to be more civilized.

No need to quote what has been said: the messages and their history is accessible.

Just bear what has been said in mind to keep ITK's communication and contribution channels being a healthy environment.

**Comment by al-sabr** [comment]
@dzenanz I added an optional parameter for the **itk\_module\_impl** with the **BYPASS\_OWNERSHIP** flag

al-sabr@d164c87

So the file generated will not end up in the **Common** folder

al-sabr@46da573

al-sabr@3819bc5

Does this make sense ?

**Comment by al-sabr** [comment]
@jhlegarreta I will try my best to keep it cool and healthy thanx for your guidance.

**Comment by al-sabr** [comment]
@dzenanz My modifications are working perfectly!!!!! Yay

Also CTK is compiling mbilog & mitk & Blueberry with my modified version of ITK with the new module.

**Comment by dzenanz** [comment]
Maybe now provide closure and point to your solution on all the opened (some of which are now closed) issues and forum posts? For bonus points, explain what the problem was, what you tried, why it didn't work and what finally worked. Maybe write this longer explanation in once place and link to it from other discussions.

**Comment by al-sabr** [comment]
I will try to do a detailed explanation of an overview of what we went through just to extract from MITK the mbilog component & Blueberry Framework and to port it for CTK so that we become totally independant of ITK & VTK & all other unnecessary dependencies from CTK concerning Medial Visualization Components.

**Comment by al-sabr** [comment]
For this ticket the solution were: 

al-sabr@46da573

al-sabr@4e31676

al-sabr@ef4785f

**Comment by al-sabr** [comment]
Is my previous post clear enough for this ticket ?

**Comment by dzenanz** [comment]
Good explanation for this ticket.

**Comment by al-sabr** [comment]
I would like to reopen this ticket because I've realized that I was trying to port ITK version 5.1.2 for Blueberry Framework. Actually I had to work on ITK version 4.13.

I redid the same work for 4.13 in a new branch and I am getting some errors I cannot understand. Here's the link for the new branch : https://github.com/al-sabr/ITK/tree/itk-4.13-foundation-internal-kwsys+vxl

![](https://user-images.githubusercontent.com/26530975/108931509-12cbc880-7648-11eb-8c3f-799b461c4521.png)

\`\`\`

9>------ Build started: Project: ITKFoundationCommon, Configuration: Debug x64 ------

9>Build started 2/24/2021 2:10:14 AM.

9>Target ResolveProjectReferences:

9>Target InitializeBuildStatus:

9>  Touching "ITKFoundationCommon.dir\\Debug\\ITKFound.1E359120.tlog\\unsuccessfulbuild".

9>Target CustomBuild:

9>  All outputs are up-to-date.

9>Target GetReferencedVCProjectsInfo:

9>  Target AddPublicIncludeDirectoriesToProjectsInfoForReference:

9>    Target AddPublicBMIsToProjectsInfoForReference:

9>Target VcpkgTripletSelection:

9>  Using triplet "x64-windows" from "G:\\vcpkg\\scripts\\buildsystems\\msbuild\\..\\..\\..\\installed\\x64-windows\\"

9>Target ClCompile:

9>  All outputs are up-to-date.

9>Target Link:

9>     Creating library G:/programming/cpp/CTK/build/ITK-build/lib/Debug/ITKFoundationCommon-4.13.lib and object G:/programming/cpp/CTK/build/ITK-build/lib/Debug/ITKFoundationCommon-4.13.exp

9>  itkObjectFactoryBase.obj : error LNK2019: unresolved external symbol "public: static struct HINSTANCE\_\_ \* \_\_cdecl itk::DynamicLoader::OpenLibrary(char const \*)" (?OpenLibrary@DynamicLoader@itk@@SAPEAUHINSTANCE\_\_@@PEBD@Z) referenced in function "private: static void \_\_cdecl itk::ObjectFactoryBase::LoadLibrariesInPath(char const \*)" (?LoadLibrariesInPath@ObjectFactoryBase@itk@@CAXPEBD@Z)

9>  itkObjectFactoryBase.obj : error LNK2019: unresolved external symbol "public: static int \_\_cdecl itk::DynamicLoader::CloseLibrary(struct HINSTANCE\_\_ \*)" (?CloseLibrary@DynamicLoader@itk@@SAHPEAUHINSTANCE\_\_@@@Z) referenced in function "public: static void \_\_cdecl itk::ObjectFactoryBase::UnRegisterAllFactories(void)" (?UnRegisterAllFactories@ObjectFactoryBase@itk@@SAXXZ)

9>  itkObjectFactoryBase.obj : error LNK2019: unresolved external symbol "public: static void \* \_\_cdecl itk::DynamicLoader::GetSymbolAddress(struct HINSTANCE\_\_ \*,char const \*)" (?GetSymbolAddress@DynamicLoader@itk@@SAPEAXPEAUHINSTANCE\_\_@@PEBD@Z) referenced in function "private: static void \_\_cdecl itk::ObjectFactoryBase::LoadLibrariesInPath(char const \*)" (?LoadLibrariesInPath@ObjectFactoryBase@itk@@CAXPEBD@Z)

9>  itkObjectFactoryBase.obj : error LNK2019: unresolved external symbol "protected: \_\_cdecl itk::DynamicLoader::DynamicLoader(void)" (??0DynamicLoader@itk@@IEAA@XZ) referenced in function "public: static class itk::SmartPointer\<class itk::DynamicLoader> \_\_cdecl itk::DynamicLoader::New(void)" (?New@DynamicLoader@itk@@SA?AV?$SmartPointer@VDynamicLoader@itk@@@2@XZ)

9>  itkOutputWindow.obj : error LNK2001: unresolved external symbol "public: virtual void \_\_cdecl itk::Win32OutputWindow::DisplayText(char const \*)" (?DisplayText@Win32OutputWindow@itk@@UEAAXPEBD@Z)

9>  itkOutputWindow.obj : error LNK2019: unresolved external symbol "protected: virtual \_\_cdecl itk::Win32OutputWindow::~Win32OutputWindow(void)" (??1Win32OutputWindow@itk@@MEAA@XZ) referenced in function "protected: virtual void \* \_\_cdecl itk::Win32OutputWindow::\`vector deleting destructor'(unsigned int)" (??\_EWin32OutputWindow@itk@@MEAAPEAXI@Z)

9>  itkThreadPool.obj : error LNK2019: unresolved external symbol "public: static unsigned int \_\_cdecl itk::ThreadPool::GetGlobalDefaultNumberOfThreadsByPlatform(void)" (?GetGlobalDefaultNumberOfThreadsByPlatform@ThreadPool@itk@@SAIXZ) referenced in function "public: static unsigned int \_\_cdecl itk::ThreadPool::GetGlobalDefaultNumberOfThreads(void)" (?GetGlobalDefaultNumberOfThreads@ThreadPool@itk@@SAIXZ)

9>  itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: static void \_\_cdecl itk::ThreadPool::PlatformCreate(void \* &)" (?PlatformCreate@ThreadPool@itk@@KAXAEAPEAX@Z) referenced in function "public: void \_\_cdecl itk::ThreadPool::AddWork(struct itk::ThreadJob const &)" (?AddWork@ThreadPool@itk@@QEAAXAEBUThreadJob@2@@Z)

9>  itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: static void \_\_cdecl itk::ThreadPool::PlatformWait(void \* &)" (?PlatformWait@ThreadPool@itk@@KAXAEAPEAX@Z) referenced in function "public: void \_\_cdecl itk::ThreadPool::WaitForJob(void \* &)" (?WaitForJob@ThreadPool@itk@@QEAAXAEAPEAX@Z)

9>  itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: static void \_\_cdecl itk::ThreadPool::PlatformSignal(void \* &)" (?PlatformSignal@ThreadPool@itk@@KAXAEAPEAX@Z) referenced in function "public: void \_\_cdecl itk::ThreadPool::AddWork(struct itk::ThreadJob const &)" (?AddWork@ThreadPool@itk@@QEAAXAEBUThreadJob@2@@Z)

9>  itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: static void \_\_cdecl itk::ThreadPool::PlatformDelete(void \* &)" (?PlatformDelete@ThreadPool@itk@@KAXAEAPEAX@Z) referenced in function "public: void \_\_cdecl itk::ThreadPool::WaitForJob(void \* &)" (?WaitForJob@ThreadPool@itk@@QEAAXAEAPEAX@Z)

9>  itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: static bool \_\_cdecl itk::ThreadPool::PlatformClose(void \* &)" (?PlatformClose@ThreadPool@itk@@KA\_NAEAPEAX@Z) referenced in function "protected: void \_\_cdecl itk::ThreadPool::DeleteThreads(void)" (?DeleteThreads@ThreadPool@itk@@IEAAXXZ)

9>  itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: void \_\_cdecl itk::ThreadPool::AddThread(void)" (?AddThread@ThreadPool@itk@@IEAAXXZ) referenced in function "public: void \_\_cdecl itk::ThreadPool::AddThreads(unsigned int)" (?AddThreads@ThreadPool@itk@@QEAAXI@Z)

9>  G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKFoundationCommon-4.13.dll : fatal error LNK1120: 13 unresolved externals

9>Done building target "Link" in project "ITKFoundationCommon.vcxproj" -- FAILED.

9>

9>Done building project "ITKFoundationCommon.vcxproj" -- FAILED.

9>

9>Build FAILED.

9>

9>itkObjectFactoryBase.obj : error LNK2019: unresolved external symbol "public: static struct HINSTANCE\_\_ \* \_\_cdecl itk::DynamicLoader::OpenLibrary(char const \*)" (?OpenLibrary@DynamicLoader@itk@@SAPEAUHINSTANCE\_\_@@PEBD@Z) referenced in function "private: static void \_\_cdecl itk::ObjectFactoryBase::LoadLibrariesInPath(char const \*)" (?LoadLibrariesInPath@ObjectFactoryBase@itk@@CAXPEBD@Z)

9>itkObjectFactoryBase.obj : error LNK2019: unresolved external symbol "public: static int \_\_cdecl itk::DynamicLoader::CloseLibrary(struct HINSTANCE\_\_ \*)" (?CloseLibrary@DynamicLoader@itk@@SAHPEAUHINSTANCE\_\_@@@Z) referenced in function "public: static void \_\_cdecl itk::ObjectFactoryBase::UnRegisterAllFactories(void)" (?UnRegisterAllFactories@ObjectFactoryBase@itk@@SAXXZ)

9>itkObjectFactoryBase.obj : error LNK2019: unresolved external symbol "public: static void \* \_\_cdecl itk::DynamicLoader::GetSymbolAddress(struct HINSTANCE\_\_ \*,char const \*)" (?GetSymbolAddress@DynamicLoader@itk@@SAPEAXPEAUHINSTANCE\_\_@@PEBD@Z) referenced in function "private: static void \_\_cdecl itk::ObjectFactoryBase::LoadLibrariesInPath(char const \*)" (?LoadLibrariesInPath@ObjectFactoryBase@itk@@CAXPEBD@Z)

9>itkObjectFactoryBase.obj : error LNK2019: unresolved external symbol "protected: \_\_cdecl itk::DynamicLoader::DynamicLoader(void)" (??0DynamicLoader@itk@@IEAA@XZ) referenced in function "public: static class itk::SmartPointer\<class itk::DynamicLoader> \_\_cdecl itk::DynamicLoader::New(void)" (?New@DynamicLoader@itk@@SA?AV?$SmartPointer@VDynamicLoader@itk@@@2@XZ)

9>itkOutputWindow.obj : error LNK2001: unresolved external symbol "public: virtual void \_\_cdecl itk::Win32OutputWindow::DisplayText(char const \*)" (?DisplayText@Win32OutputWindow@itk@@UEAAXPEBD@Z)

9>itkOutputWindow.obj : error LNK2019: unresolved external symbol "protected: virtual \_\_cdecl itk::Win32OutputWindow::~Win32OutputWindow(void)" (??1Win32OutputWindow@itk@@MEAA@XZ) referenced in function "protected: virtual void \* \_\_cdecl itk::Win32OutputWindow::\`vector deleting destructor'(unsigned int)" (??\_EWin32OutputWindow@itk@@MEAAPEAXI@Z)

9>itkThreadPool.obj : error LNK2019: unresolved external symbol "public: static unsigned int \_\_cdecl itk::ThreadPool::GetGlobalDefaultNumberOfThreadsByPlatform(void)" (?GetGlobalDefaultNumberOfThreadsByPlatform@ThreadPool@itk@@SAIXZ) referenced in function "public: static unsigned int \_\_cdecl itk::ThreadPool::GetGlobalDefaultNumberOfThreads(void)" (?GetGlobalDefaultNumberOfThreads@ThreadPool@itk@@SAIXZ)

9>itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: static void \_\_cdecl itk::ThreadPool::PlatformCreate(void \* &)" (?PlatformCreate@ThreadPool@itk@@KAXAEAPEAX@Z) referenced in function "public: void \_\_cdecl itk::ThreadPool::AddWork(struct itk::ThreadJob const &)" (?AddWork@ThreadPool@itk@@QEAAXAEBUThreadJob@2@@Z)

9>itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: static void \_\_cdecl itk::ThreadPool::PlatformWait(void \* &)" (?PlatformWait@ThreadPool@itk@@KAXAEAPEAX@Z) referenced in function "public: void \_\_cdecl itk::ThreadPool::WaitForJob(void \* &)" (?WaitForJob@ThreadPool@itk@@QEAAXAEAPEAX@Z)

9>itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: static void \_\_cdecl itk::ThreadPool::PlatformSignal(void \* &)" (?PlatformSignal@ThreadPool@itk@@KAXAEAPEAX@Z) referenced in function "public: void \_\_cdecl itk::ThreadPool::AddWork(struct itk::ThreadJob const &)" (?AddWork@ThreadPool@itk@@QEAAXAEBUThreadJob@2@@Z)

9>itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: static void \_\_cdecl itk::ThreadPool::PlatformDelete(void \* &)" (?PlatformDelete@ThreadPool@itk@@KAXAEAPEAX@Z) referenced in function "public: void \_\_cdecl itk::ThreadPool::WaitForJob(void \* &)" (?WaitForJob@ThreadPool@itk@@QEAAXAEAPEAX@Z)

9>itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: static bool \_\_cdecl itk::ThreadPool::PlatformClose(void \* &)" (?PlatformClose@ThreadPool@itk@@KA\_NAEAPEAX@Z) referenced in function "protected: void \_\_cdecl itk::ThreadPool::DeleteThreads(void)" (?DeleteThreads@ThreadPool@itk@@IEAAXXZ)

9>itkThreadPool.obj : error LNK2019: unresolved external symbol "protected: void \_\_cdecl itk::ThreadPool::AddThread(void)" (?AddThread@ThreadPool@itk@@IEAAXXZ) referenced in function "public: void \_\_cdecl itk::ThreadPool::AddThreads(unsigned int)" (?AddThreads@ThreadPool@itk@@QEAAXI@Z)

9>G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKFoundationCommon-4.13.dll : fatal error LNK1120: 13 unresolved externals

9>    0 Warning(s)

9>    14 Error(s)

9>

9>Time Elapsed 00:00:01.17

\========== Build: 8 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

\`\`\`

**Comment by al-sabr** [comment]
Can someone tell me why it is compiling but not linking?
