### ISSUE TITLE
ITK_EXERCISE_BASIC_OBJECT_METHODS failures in ITKReview module

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#2719]
### Description

`ITK_EXCERCISE_BASIC_OBJECT_METHODS` are not compiling with a few classes from the `ITKReview` module:

https://open.cdash.org/viewBuildError.php?buildid=7442857

```
[5339/6175] Building CXX object Modules/Segmentation/SignedDistanceFunction/test/CMakeFiles/ITKSignedDistanceFunctionTestDriver.dir/itkSphereSignedDistanceFunctionTest.cxx.o
[5340/6175] Building CXX object Modules/Filtering/Smoothing/test/CMakeFiles/ITKSmoothingGTestDriver.dir/itkMedianImageFilterGTest.cxx.o
[5341/6175] Building CXX object Modules/Nonunit/Review/test/CMakeFiles/ITKReviewTestDriver.dir/itkDiscreteGaussianDerivativeImageFunctionTest.cxx.o
[5342/6175] Building CXX object Modules/Filtering/Smoothing/test/CMakeFiles/ITKSmoothingGTestDriver.dir/itkMeanImageFilterGTest.cxx.o
[5343/6175] Building CXX object Modules/Segmentation/SignedDistanceFunction/test/CMakeFiles/ITKSignedDistanceFunctionTestDriver.dir/itkPCAShapeSignedDistanceFunctionTest.cxx.o
[5344/6175] Building CXX object Modules/Nonunit/Review/test/CMakeFiles/ITKReviewTestDriver.dir/itkLabelGeometryImageFilterTest.cxx.o
FAILED: Modules/Nonunit/Review/test/CMakeFiles/ITKReviewTestDriver.dir/itkLabelGeometryImageFilterTest.cxx.o 
/usr/bin/c++  -I/.../ITK/Modules/IO/CSV/include -IModules/ThirdParty/Eigen3/src -IModules/ThirdParty/KWIML/src -I/.../ITK/Modules/ThirdParty/KWIML/src -IModules/ThirdParty/KWSys/src -I/.../ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/.../ITK/Modules/ThirdParty/VNL/src/vxl/vcl -I/.../ITK/Modules/ThirdParty/VNL/src/vxl/core -IModules/ThirdParty/VNL/src/vxl/v3p/netlib -IModules/ThirdParty/VNL/src/vxl/vcl -IModules/ThirdParty/VNL/src/vxl/core -IModules/Core/Common -I/.../ITK/Modules/Core/Common/include -IModules/IO/ImageBase -I/.../ITK/Modules/IO/ImageBase/include -I/.../ITK/Modules/IO/TIFF/include -I/.../ITK/Modules/IO/LSM/include -I/.../ITK/Modules/Filtering/ImageFilterBase/include -IModules/ThirdParty/Netlib -I/.../ITK/Modules/Numerics/Statistics/include -I/.../ITK/Modules/Core/Transform/include -I/.../ITK/Modules/Core/Mesh/include -I/.../ITK/Modules/Core/QuadEdgeMesh/include -I/.../ITK/Modules/Segmentation/Voronoi/include -I/.../ITK/Modules/IO/MeshBase/include -I/.../ITK/Modules/IO/MeshBYU/include -I/.../ITK/Modules/IO/MeshFreeSurfer/include -I/.../ITK/Modules/IO/MeshGifti/include -I/.../ITK/Modules/IO/MeshOBJ/include -I/.../ITK/Modules/IO/MeshOFF/include -I/.../ITK/Modules/IO/MeshVTK/include -I/.../ITK/Modules/IO/Mesh/include -I/.../ITK/Modules/Core/FiniteDifference/include -I/.../ITK/Modules/Filtering/CurvatureFlow/include -I/.../ITK/Modules/Core/ImageAdaptors/include -I/.../ITK/Modules/Core/ImageFunction/include -I/.../ITK/Modules/Filtering/ImageGrid/include -I/.../ITK/Modules/Filtering/AnisotropicSmoothing/include -I/.../ITK/Modules/Filtering/ImageCompose/include -IModules/ThirdParty/ZLIB/src -I/.../ITK/Modules/ThirdParty/ZLIB/src -IModules/ThirdParty/MetaIO/src/MetaIO/src -I/.../ITK/Modules/ThirdParty/MetaIO/src/MetaIO/src -I/.../ITK/Modules/Core/SpatialObjects/include -I/.../ITK/Modules/Filtering/ImageStatistics/include -I/.../ITK/Modules/Filtering/Path/include -I/.../ITK/Modules/Filtering/ImageIntensity/include -I/.../ITK/Modules/Filtering/ImageLabel/include -I/.../ITK/Modules/Filtering/LabelMap/include -I/.../ITK/Modules/Filtering/Thresholding/include -I/.../ITK/Modules/Segmentation/ConnectedComponents/include -I/.../ITK/Modules/Filtering/MathematicalMorphology/include -I/.../ITK/Modules/Filtering/BinaryMathematicalMorphology/include -I/.../ITK/Modules/Numerics/NarrowBand/include -I/.../ITK/Modules/Filtering/DistanceMap/include -I/.../ITK/Modules/Filtering/FastMarching/include -I/.../ITK/Modules/Filtering/ImageCompare/include -I/.../ITK/Modules/Filtering/Smoothing/include -I/.../ITK/Modules/Filtering/ImageGradient/include -I/.../ITK/Modules/Filtering/ImageSources/include -I/.../ITK/Modules/Filtering/ImageFeature/include -I/.../ITK/Modules/Numerics/Optimizers/include -I/.../ITK/Modules/Segmentation/SignedDistanceFunction/include -I/.../ITK/Modules/Segmentation/LevelSets/include -I/.../ITK/Modules/Filtering/AntiAlias/include -I/.../ITK/Modules/Numerics/Polynomials/include -I/.../ITK/Modules/Filtering/BiasCorrection/include -I/.../ITK/Modules/Segmentation/Classifiers/include -I/.../ITK/Modules/Segmentation/DeformableMesh/include -I/.../ITK/Modules/Filtering/DiffusionTensorImage/include -I/.../ITK/Modules/Filtering/DisplacementField/include -I/.../ITK/Modules/Numerics/Eigen/include -I/.../ITK/Modules/Filtering/FFT/include -I/.../ITK/Modules/IO/BMP/include -I/.../ITK/Modules/IO/BioRad/include -I/.../ITK/Modules/IO/GDCM/include -I/.../ITK/Modules/IO/IPL/include -I/.../ITK/Modules/IO/GE/include -I/.../ITK/Modules/IO/GIPL/include -I/.../ITK/Modules/IO/JPEG/include -I/.../ITK/Modules/IO/Meta/include -I/.../ITK/Modules/IO/NIFTI/include -I/.../ITK/Modules/IO/NRRD/include -I/.../ITK/Modules/IO/PNG/include -I/.../ITK/Modules/IO/RAW/include -I/.../ITK/Modules/IO/Siemens/include -I/.../ITK/Modules/IO/SpatialObjects/include -I/.../ITK/Modules/IO/Stimulate/include -I/.../ITK/Modules/IO/TransformFactory/include -I/.../ITK/Modules/IO/TransformBase/include -I/.../ITK/Modules/IO/TransformHDF5/include -I/.../ITK/Modules/IO/TransformInsightLegacy/include -I/.../ITK/Modules/IO/TransformMatlab/include -I/.../ITK/Modules/IO/VTK/include -I/.../ITK/Modules/IO/XML/include -I/.../ITK/Modules/Filtering/ImageFusion/include -I/.../ITK/Modules/Segmentation/KLMRegionGrowing/include -I/.../ITK/Modules/Segmentation/LabelVoting/include -I/.../ITK/Modules/Segmentation/MarkovRandomFieldsClassifiers/include -IModules/ThirdParty/OpenJPEG/src/openjpeg -I/.../ITK/Modules/ThirdParty/OpenJPEG/src/openjpeg -I/.../ITK/Modules/Registration/Common/include -I/.../ITK/Modules/Registration/PDEDeformable/include -I/.../ITK/Modules/Filtering/QuadEdgeMeshFiltering/include -I/.../ITK/Modules/Segmentation/RegionGrowing/include -I/.../ITK/Modules/Filtering/SpatialFunction/include -I/.../ITK/Modules/Bridge/VTK/include -I/.../ITK/Modules/Segmentation/Watersheds/include -I/.../ITK/Modules/Nonunit/Review/include -I/.../ITK/Modules/ThirdParty/DoubleConversion/src -IModules/ThirdParty/DoubleConversion/src/double-conversion -I/.../ITK/Modules/Core/TestKernel/include -I/.../ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo -I/.../ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl -IModules/ThirdParty/VNL/src/vxl/core/vnl -isystem /.../ITK/Modules/ThirdParty/Eigen3/src/itkeigen/.. -fPIC -Wall -Wshadow -Wno-uninitialized -Wextra  -mtune=generic -march=corei7 -Wcast-align -Wdisabled-optimization -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel  -g -fPIE -std=c++14 -MD -MT Modules/Nonunit/Review/test/CMakeFiles/ITKReviewTestDriver.dir/itkLabelGeometryImageFilterTest.cxx.o -MF Modules/Nonunit/Review/test/CMakeFiles/ITKReviewTestDriver.dir/itkLabelGeometryImageFilterTest.cxx.o.d -o Modules/Nonunit/Review/test/CMakeFiles/ITKReviewTestDriver.dir/itkLabelGeometryImageFilterTest.cxx.o -c /.../ITK/Modules/Nonunit/Review/test/itkLabelGeometryImageFilterTest.cxx
In file included from Modules/Nonunit/Review/test/itkLabelGeometryImageFilterTest.cxx:26:
/.../ITK/Modules/Nonunit/Review/test/itkLabelGeometryImageFilterTest.cxx: In function 'int LabelGeometryImageFilterTest(std::string, std::string, std::string, std::string, std::string)':
Modules/Core/TestKernel/include/itkTestingMacros.h:69:51: error: 'Superclass' has not been declared
   69 |   std::cout << "Name of Superclass = " << object->Superclass::GetNameOfClass() << std::endl;                           \
      |          
```

### Steps to Reproduce

These can be reproduced locally by turning on `Module_ITKReview`.

### Expected behavior

No build errors.

### Additional Information

I see a `Superclass` type alias here:

https://github.com/InsightSoftwareConsortium/ITK/blob/fa5b8266a559374ef8630f25c7bb0ecc7b7b9c31/Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.h#L83

@jhlegarreta @dzenanz any ideas?

**Comment by jhlegarreta** [comment]
You are right @thewtex : these were introduced in PR #2653 by me :pensive: . They were detected once the PR got merged (all Azure checks were passing, maybe because the Review module does not get tested dynamically?), and we had some exchange on the PR to try to identify the issue to no avail.

@dzenanz opened issue #2676 to keep track of it.

**Comment by dzenanz** [comment]
Closing as a duplicate of #2676.
