### PR TITLE
Switch MINC upstream branch from develop to master and update it

### LINKED ISSUE #4552: GDCM fails to compile using MSVC 2019, 2022 after bump to 3.0.23
### Description

GDCM fails to compile using MSVC 2019, 2022:
https://open.cdash.org/index.php?project=Insight&date=2024-03-26
vs
https://open.cdash.org/index.php?project=Insight&date=2024-03-27

with the errors:
```
T:\Dashboard\ITK\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmSystem.cxx(905,3):
error C3861: 'gettimeofday': identifier not found
```

and
```
T:\Dashboard\ITK\Modules\ThirdParty\MINC\src\libminc\volume_io\Prog_utils\time.c(133,20):
error C2079: 'tv' uses undefined struct 'timeval'
```

Errors appeared after GDCM was bumped from 3.0.22 to 3.0.23 in 919cf42.

Not sure why this was not reported by Azure Pipelines, which uses MSVC 2019:
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Testing/ContinuousIntegration/AzurePipelinesWindows.yml#L83

### Steps to Reproduce

Have a Windows system with MSVC 2019 or 2022 (may happen on newer versions)
1. Clone ITK `master`
2. Configure and generate
3. Build project

### Expected behavior

No compiler errors are reported.

### Actual behavior

Build fails with the errors:
```
T:\Dashboard\ITK\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmSystem.cxx(905,3):
error C3861: 'gettimeofday': identifier not found
```

and
```
T:\Dashboard\ITK\Modules\ThirdParty\MINC\src\libminc\volume_io\Prog_utils\time.c(133,20):
error C2079: 'tv' uses undefined struct 'timeval'
```

### Reproducibility

100%

### Versions

ITK `master`.

### Environment

OS: Windows
Compiler: MSVC 2019, 2022

### Additional Information

File at issue at GDCM 3.0.23:
https://github.com/malaterre/GDCM/blob/v3.0.23/Source/Common/gdcmSystem.cxx

File at issue at GDCM 3.0.22:
https://github.com/malaterre/GDCM/blob/v3.0.22/Source/Common/gdcmSystem.cxx

They are exactly the same, so maybe it is this block, where `gettimeofday` is defined, that is not being compiled: https://github.com/malaterre/GDCM/blob/master/Source/Common/gdcmSystem.cxx#L644-L725

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #4552.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Review by vfonov — APPROVED** [review]

**Review by jhlegarreta — APPROVED** [review]
Thanks for having devoted time to this issue Dženan.

**Review by thewtex — APPROVED** [review]
