### PR TITLE
ENH: Update vendored Eigen3 to 5.0.1+master; verify USE_SYSTEM 3.3/3.4/5.x

### PR DESCRIPTION
**Pull request by hjmjohnson**
Vendors Eigen master post-5.0.1 (gitlab `libeigen/eigen` tip `fef1460e`, late April 2026; `EIGEN_VERSION_STRING="5.0.1-dev+master"`) via the canonical `UpdateFromUpstream.sh` flow, and demonstrates `ITK_USE_SYSTEM_EIGEN=ON` against system Eigen 3.3.9, 3.4.0, and 5.0.1. The 3.3 minimum-version gate is preserved.

<details>
<summary>Acceptance matrix (build + Eigen-related tests)</summary>

| Row | Eigen source | Build | Tests |
|---|---|---|---|
| A  | Vendored gitlab-tip via ISC fork `5a7cc61d6` (Eigen 5.0.1+master) | 5246 / 5246 | 11 / 11 |
| B0 | conda-forge `eigen=3.3.9` (proves min-version gate) | 5974 / 5974 | 11 / 11 |
| B  | conda-forge `eigen=3.4.0` | 5974 / 5974 | 11 / 11 |
| C  | conda-forge `eigen=5.0.1` | 5974 / 5974 | 11 / 11 |

The 11 tests: `itkSymmetricEigenAnalysisTest`, `itkEigenAnalysis2DImageFilterTest`, `itkSymmetricEigenAnalysisImageFilterTest{OrderByValue,OrderByMagnitude,DoNotOrder}`, `vnl_algo_test_{complex,generalized,real,symmetric}_eigensystem`, `ITKEigenKWStyleTest`, `ITKEigenInDoxygenGroup`.

</details>

<details>
<summary>What changed in the vendored tree</summary>

- `UpdateFromUpstream.sh` tag bumped to the new ISC fork tag (suffix `-fef1460ek`). Whitelist gained `AccelerateSupport`, `KLUSupport`, `ThreadPool`, `Version` (the `Eigen/Version` header is required because Eigen 5 moved `EIGEN_{MAJOR,MINOR,PATCH}_VERSION` out of `src/Core/util/Macros.h`).
- The vendored `src/itkeigen/CMakeLists.txt` version parser was rewritten on the fork (`be4bdb732`) to read `Eigen/Version` (semver `MAJOR.MINOR.PATCH`) for Eigen 5+, falling back to `Macros.h` (`WORLD.MAJOR.MINOR`) for legacy 3.4.x. `Eigen3ConfigVersion.cmake` now reports `PACKAGE_VERSION "5.0.1"`.
- One merge conflict during the subtree import, in `Eigen/src/Core/products/SelfadjointMatrixVector.h`: Eigen 5 fully rewrote that kernel into 4-col / 2-col / 1-col phases, already initializing accumulators with `pzero(Packet{})`. Resolved by taking upstream entirely — the older in-tree COMP patch `91f6232` ("pzero(Packet{}) for SelfadjointMatrixVector accumulators") is subsumed and obsolete.

</details>

<details>
<summary>ISC fork (InsightSoftwareConsortium/eigen) state</summary>

- New tag at `5a7cc61d6`.
- `for/itk-master` advanced to `5a7cc61d6`.
- Three ITK-overlay commits on top of gitlab `fef1460e`: CMake override (`be4bdb732`), `.gitattributes` lapacke relax (`fb7121abd`), and `README.kitware.md` (`5a7cc61d6`).

</details>

<details>
<summary>Outer-module CMake</summary>

`Modules/ThirdParty/Eigen3/CMakeLists.txt` keeps `_Eigen3_min_version=3.3` (no upper bound). `find_package(Eigen3 REQUIRED CONFIG)` plus the explicit `VERSION_LESS` check accepts both 3.x and 5.x system installs without modification.

</details>

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@greptile review

File: Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt [hunk 1]
```diff
@@ -6,6 +6,8 @@ project(Eigen3)
 # ITK doesn't compile anything here, just generates targets for the INTERFACE library.
 if(FALSE)
 
+cmake_minimum_required(VERSION 3.10.0)
```
Comment (dzenanz) [inline Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt:9]: Should we increase this to 3.16.3? Also, there is `cmake_minimum_required(VERSION 3.10.2)` on line 2.

**Review by dzenanz — COMMENTED** [review]
This is not eigen `5.0.1`, but `5.0.1+`.

File: Modules/ThirdParty/Eigen3/src/itkeigen/cmake/Eigen3Config.cmake.in [hunk 2]
```diff
@@ -3,6 +3,6 @@
 
 @PACKAGE_INIT@
 
-if (NOT TARGET eigen)
-  include ("${CMAKE_CURRENT_LIST_DIR}/@EIGEN3_TARGETS_FILE@")
-endif ()
+if (NOT TARGET Eigen3::Eigen)
+  include ("${CMAKE_CURRENT_LIST_DIR}/Eigen3Targets.cmake")
+endif (NOT TARGET Eigen3::Eigen)
```
[the remark this answers is not in the document]
Comment (hjmjohnson) [reply Modules/ThirdParty/Eigen3/src/itkeigen/cmake/Eigen3Config.cmake.in:8]: Fixed in fb8e6edef0 — restored the `@EIGEN3_TARGETS_FILE@` substitution so the configured `ITKInternalEigen3Config.cmake` includes `ITKInternalEigen3Targets.cmake` rather than the eigen_external file.

File: Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt [hunk 3]
```diff
@@ -896,6 +949,8 @@ add_library (ITKInternalEigen3::Eigen ALIAS eigen_internal)
 # This would wrongly enforce EIGEN_MPL2_ONLY to other libraries using Eigen.
 # We wrap this definition in ITK_USE_EIGEN_MPL2_ONLY, and only enabling it internally in the dashboards and CI,
 # to avoid introducing GPL code from Eigen3 internally in ITK.
+option(ITK_USE_EIGEN_MPL2_ONLY "Set compile definition EIGEN_MPL2_ONLY for ITKInternalEigen3." OFF)
+mark_as_advanced(ITK_USE_EIGEN_MPL2_ONLY)
```
[the remark this answers is not in the document]
Comment (hjmjohnson) [reply Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt]: Fixed in fb8e6edef0 — removed the duplicate `option(ITK_USE_EIGEN_MPL2_ONLY)` declaration; the canonical declaration at line 844 is the only one now, with a one-line pointer comment where the duplicate used to be.

File: Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt [hunk 4]
```diff
@@ -905,10 +960,41 @@ endif()
 #   #include <itkeigen/Eigen/x>
 # INSTALL: headers require pre-prend itkeigen/Eigen/X.
 target_include_directories (eigen_internal SYSTEM INTERFACE
-  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
-  "$<INSTALL_INTERFACE:$<INSTALL_PREFIX>/${ITK3P_INSTALL_INCLUDE_DIR}/itkeigen>;"
+  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/..>
+  # $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/..>
```
[the remark this answers is not in the document]
Comment (hjmjohnson) [reply Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt]: Fixed in fb8e6edef0 — removed the commented-out generator expression. Eigen 5's vendored header tree is fully sourced from `CMAKE_CURRENT_SOURCE_DIR` (no configured headers land in the binary dir for this module), so the line was dead code.

File: Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt (hunk 1 above)
Comment (hjmjohnson) [reply Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt:9]: Bumped to 3.16.3 in a3699e056a. Also replaced the surrounding `if(FALSE) ... endif()` wrapper with CMake's `#[[ ... #]]` multiline-comment markers (with explicit `ITK - START/STOP DISABLE UPSTREAM EIGEN LOGIC` labels), so IDEs render the wrapped block as dimmed dead code; the inner `cmake_minimum_required(VERSION 3.10.0)` is now part of the comment and remains inert as before.

**Comment by hjmjohnson** [comment]
@dzenanz You are correct — the vendored content is not the released Eigen `5.0.1` but rather the master branch tip just past it. Upstream's own `Eigen/Version` header self-identifies as `EIGEN_VERSION_STRING="5.0.1-dev+master"`. Fixed in 016f9acc66:

- PR title and opening sentence now say "Eigen master post-5.0.1" (with the upstream version-string explicitly noted).
- Acceptance matrix row A relabeled to `(Eigen 5.0.1+master)` for the vendored ISC fork `5a7cc61d6` (vs row C which keeps `conda-forge eigen=5.0.1` since that is in fact the released package).
- Commit `90ff8c1e76`'s rationale was reworded to use the same phrasing.

**Comment by hjmjohnson** [comment]
ITK.Windows builds 16039 and 16040 both failed in ~3 min due to a Chocolatey infrastructure flake, not anything in this PR. Fetched the Azure DevOps timeline + log of build 16040 step #8:

```
Failed to fetch results from V2 feed at
'https://community.chocolatey.org/api/v2/Packages(Id='ccache',Version='4.13.5')'
with following message : Response status code does not indicate success:
504 (Gateway Timeout).
Unable to find package 'ccache'.
Chocolatey installed 0/0 packages.
```

The pipeline's `Install dependencies` step swallowed the 504 silently (choco exited 0 even though 0 packages installed); every later `ccache` invocation then hit `command not found` → exit 127, and `Build and test` was skipped. ITK.Windows is green on `main` (`a2458bf7b9`) and on every recent merge, including the small Eigen tweak in #6166, so this isn't an Eigen-5+master compatibility issue.

Re-triggering with `/azp run ITK.Windows` to get a fresh chocolatey hit. (Possible separate hardening: `choco install` should be guarded with `if errorlevel 1 exit /b 1` or equivalent so a 504 fails the step instead of silently passing.)

File: Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt [hunk 5]
```diff
@@ -596,7 +596,10 @@ if (EIGEN_BUILD_TESTING)
     #         throw exceptions - in particular in the unit tests we are throwing extra many
     #         exceptions to cover indexing errors.
     # C4505 - unreferenced local function has been removed (impossible to deactivate selectively)
-    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHsc /wd4127 /wd4505 /wd4714")
+    # C4750 - function with _alloca() inlined into a loop; emitted from
+    #         Eigen/src/Eigenvalues/Tridiagonalization.h on MSVC. Eigen's
+    #         alloca-based small-allocation path is intentional and benign here.
+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHsc /wd4127 /wd4505 /wd4714 /wd4750")
```
Comment (blowekamp) [inline Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt]: It is not obvious where these compilation flags will apply. Eigen is just a header library so the flag won't be applied to compile eigen files. The CMAKE_CXX_FLAGS is just a local variable, and does not affect the global ( and it shouldn't). So I am not sure what this does.

The EHsc flag adjusts exception handling which should not be applied globally. Also if these flags were added to the interface flag of the library, they would be added to the ITKCommon, and suppressed for just about all of the tool kit.

**Review by blowekamp — COMMENTED** [review]
Looking good.

Thank you for updating the library. After I refactored from an off fetch_content in the root of the project to an itk standard third party library I ran out of steam to upgrade.

There were some rather odd usages of Eigen in external modules. The intention moving forward is just have it behave just like a normal ITK interface library without special cmake code.

File: Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt (hunk 5 above)
Comment (hjmjohnson) [reply Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt]: You're right on every count, thanks for the careful review. Reverted in `be77e85615`.

To unpack what I had wrong:

1. **`set(CMAKE_CXX_FLAGS …)` in the vendored Eigen tree is dead code for ITK** — Eigen is header-only, no Eigen-internal `.cxx` is compiled by ITK, and `CMAKE_CXX_FLAGS` is local to the subdirectory anyway. My `/wd4750` addition there did nothing.

2. **The fallback I considered — attaching `/wd4750` to `eigen_internal` INTERFACE — would have hit your second concern.** Verified: `Modules/Core/Common/itk-module.cmake:21` lists `ITKEigen3` in `DEPENDS`, so the INTERFACE flag would have propagated through ITKCommon to ~every consumer in the toolkit. Suppressing C4750 globally is not what we want; the warning is real for non-Eigen code that genuinely shouldn't be allocating in a loop.

3. **The pragmatic fix is the dashboard.** ITK already has `.*Modules/ThirdParty/Eigen3/.*warning:.*` in `CMake/CTestCustom.cmake.in:134` that hides GCC/Clang warnings from CDash. MSVC's warning format is `warning C####:` rather than `warning:`, so the existing regex didn't catch C4750. Added a sibling regex that does.

Net behaviour: the compiler still emits C4750 in the build log, reviewers can see it, but the dashboard's warning count ignores it — same scope the GCC/Clang exception has always had.

Comment (hjmjohnson) [reply Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt]: Great catch, Brad.  And thanks for noting, "if these flags were added to the interface flag of the library, they would be added to the ITKCommon, "  I had started implementing exactly that,  and it would have been a mistake.  

Working on suppressing in "CMake/CTestCustom.cmake.in". It might take a few CI cycles to fix up.

**Comment by hjmjohnson** [comment]
@phcerdan Do you have any suggestions for how this PR can be better instrumented?

**Comment by phcerdan** [comment]
It's looking good to me @hjmjohnson, you performed all the needed steps for updating a remote.

@blowekamp might be more up-to-date after all the work he did on standardizing eigen.

**Review by phcerdan — APPROVED** [review]

**Comment by hjmjohnson** [comment]
> There were some rather odd usages of Eigen in external modules. The intention moving forward is just have it behave just like a normal ITK interface library without special cmake code.

@blowekamp I am uncertain if your previous comment is requesting changes to this PR, or indicating work that was already done.  If this PR is OK as is, please approve and merge.  If there are additions, please indicate if they should be on this PR, or a followup and what is needed.  Thank you, Hans

**Comment by blowekamp** [comment]
The TVProx was one remote module I spent some time on refactoring to work with the refactored Eigen and the updated ITK CMake. There is still an outstanding PR regarding these changes. The CI could not be made green due to the changes with Eigan being after the most recent tag:
https://github.com/InsightSoftwareConsortium/ITKTotalVariation/pull/57

Eigan is use more by remote modules than internal, which should be an important part of testing. There may be other remote modules that may still have issues with the previous updates.

This is all to say that Eigan usage is rough around the edges, and needs some extra checks. There were options related to what code was included and compile time defines that I could not make sense of too.

Also, the ITK on conda-forge is using the latest eigen with out problems, but that usage is minimum,

**Comment by hjmjohnson** [comment]
Deep-dive verified PR #6176 builds cleanly end-to-end (full ITK 6156/6156 targets) and exports a correctly-configured vendored Eigen 5; smoke-tested via `Eigen3::Eigen` IMPORTED target. **PR #6176 stands on its own — no changes needed here for downstream consumption.**

The deep dive did surface one pre-existing ITK architectural detail that affects InsightSoftwareConsortium/ITKTotalVariation#57's modern-target-interfaces refactor (proxTV's `<Eigen/Dense>` not resolving against the vendored Eigen). That's being addressed in a separate follow-up — see below.

<details>
<summary>What was tested</summary>

| Tier | What | Result |
|---|---|---|
| 0 | Direct `Eigen3::Eigen` smoke test against vendored Eigen 5 (`EIGEN_WORLD.MAJOR.MINOR = 3.5.0`) | ✅ |
| 1 | Full ITK build with `ITK_BUILD_DEFAULT_MODULES=ON` + `Module_TotalVariation=ON` on Ubuntu 24.04 / gcc 13.3 / CMake 4.2.1 | ✅ 6156/6156, zero failures |
| 2 | ITKTotalVariation `main` (`94b85b4`) as remote module against PR #6176 | ✅ proxTV builds, `itkProxTVImageFilterTest` passes — but silently used system Eigen 3.4 because the longstanding `set(Eigen3_DIR "${ITKInternalEigen3_DIR}")` plumbing in TotalVariation reads an empty `ITKInternalEigen3_DIR` at in-tree build time |
| 3 | ITKTotalVariation #57 (`39e849e blowekamp/cmake_interface_update`) as remote module against PR #6176 | ❌ proxTV `lapackFunctionsWrap.cpp:11:10: fatal error: Eigen/Dense: No such file or directory` — but **not a PR #6176 bug**; root cause below |

</details>

<details>
<summary>Architectural finding — pre-existing in ITK, exposed by ITKTotalVariation#57</summary>

ITK ships its vendored Eigen3 headers at:
```
Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/<header>
```

ITK's own internal code uses a special macro form `ITK_EIGEN(<header>)` that expands to `<itkeigen/Eigen/<header>>`, so an include path of `${ITKEigen3_SOURCE_DIR}/src` (the **parent** of `itkeigen/`) lets the compiler append `/itkeigen/Eigen/<header>`. ITK proper builds fine with this convention.

`Modules/ThirdParty/Eigen3/CMakeLists.txt:58` (vendored case):
```cmake
set(ITKEigen3_INCLUDE_DIRS ${ITKEigen3_SOURCE_DIR}/src)
```

This single path then flows into `INTERFACE_INCLUDE_DIRECTORIES` of both exported targets:

```cmake
# /tmp/itk-pr6176-build/ITKTargets.cmake:99-107
set_target_properties(ITK::eigen_internal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES ".../Modules/ThirdParty/Eigen3/src/itkeigen/..")  # → .../Eigen3/src

set_target_properties(ITK::ITKEigen3Module PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES ".../Eigen3/src;.../Modules/ThirdParty/Eigen3/src"
  INTERFACE_LINK_LIBRARIES "ITK::eigen_internal")
```

External consumers that legitimately use the upstream-Eigen convention `<Eigen/<header>>` (proxTV, anything pulled via `FetchContent` that wraps real Eigen) need an include path of `.../Eigen3/src/itkeigen` — **one level deeper**. No exported IMPORTED target provides that.

The `Eigen3::Eigen` target produced by Eigen's own `target_include_directories(eigen INTERFACE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>)` *does* have the correct path, but it's declared as `add_library(Eigen3::Eigen ALIAS eigen)` — an in-source-scope ALIAS, invisible to FetchContent sub-builds (verified empirically: rewriting ITKTotalVariation#57 to link `Eigen3::Eigen` triggers `Target "Eigen3::Eigen" was not found`).

This is **not introduced by PR #6176** — `upstream/main` has the same setup. PR #6176 inherits it. The Eigen 5 update doesn't change the vendored include layout.

</details>

<details>
<summary>Proposed resolution — separate follow-up PR</summary>

Single-file, one-block change to `Modules/ThirdParty/Eigen3/CMakeLists.txt:58`:

```diff
-  set(ITKEigen3_INCLUDE_DIRS ${ITKEigen3_SOURCE_DIR}/src)
+  set(
+    ITKEigen3_INCLUDE_DIRS
+    ${ITKEigen3_SOURCE_DIR}/src
+    ${ITKEigen3_SOURCE_DIR}/src/itkeigen
+  )
```

Both paths flow into `INTERFACE_INCLUDE_DIRECTORIES` of `ITK::ITKEigen3Module` / `ITK::eigen_internal`. ITK's own `<itkeigen/Eigen/<header>>` consumers continue to find their headers via the first entry; external consumers using `<Eigen/<header>>` find theirs via the second. No source-code changes anywhere else.

After this lands:
- ITKTotalVariation#57 builds against vendored Eigen 5 with no further changes (`proxTV_Eigen_LIBRARIES = ITK::ITKEigen3Module` becomes correct).
- The longstanding "silent fall-through to system Eigen" bug in ITKTotalVariation `main` (where `set(Eigen3_DIR "${ITKInternalEigen3_DIR}")` reads an empty value) becomes moot, since direct linking against `ITK::ITKEigen3Module` now works without the broken `Eigen3_DIR` shim.

Branch: `hjmjohnson:eigen-include-itkeigen-path` (off `upstream/main`, single COMP commit `d36276b8a9`). Local end-to-end verification (full ITK + ITKTotalVariation#57 + proxTV) is in progress; PR will be opened once the build settles.

</details>

<details>
<summary>What this PR (#6176) does not need to change</summary>

Nothing. The findings above are independent of the Eigen 5 vendored update; the include-dir omission predates this PR by years and would surface against ITKTotalVariation#57 regardless of which Eigen version is vendored. PR #6176 is verified ready on its own merits — vendored Eigen 5 builds clean, exports the correct `Eigen3::Eigen` (in-source) and exposes its include path through both ITK targets identically to how `upstream/main` did before this PR.

</details>

**Comment by seanm** [comment]
This MR broke my build:

```
In file included from /some/path/ITK-install/include/ITK/itkAffineTransform.h:21:
In file included from /some/path/ITK-install/include/ITK/itkMatrixOffsetTransformBase.h:24:
In file included from /some/path/ITK-install/include/ITK/itkTransform.h:24:
In file included from /some/path/ITK-install/include/ITK/itkSymmetricSecondRankTensor.h:29:
/some/path/ITK-install/include/ITK/itkSymmetricEigenAnalysis.h:23:10: fatal error: 'itkeigen/Eigen/Eigenvalues' file not found
#include ITK_EIGEN(Eigenvalues)
         ^~~~~~~~~~~~~~~~~~~~~~
```

Bisect results:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
https://github.com/InsightSoftwareConsortium/ITK/commit/bc87d16685adbadd975a619beef26a030a53b922
https://github.com/InsightSoftwareConsortium/ITK/commit/64ddc6660c82966f47cbf36ef25175a8792c7df0
We cannot bisect more!
