### PR TITLE
COMP: Fix `Regitration::FEM` module `PrintSelf` compiler errors

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix miscellaneous compiler errors in `Registration::FEM` module classes' `PrintSelf` methods.

Fixes:
```
ITK\Modules\Registration\FEM\include\itkFEMFiniteDifferenceFunctionLoad.hxx(358,3):
error C2440:
'static_cast':
cannot convert from 'const itk::fem::Solution::ConstPointer' to 'const itk::LightObject *'
```

```
ITK\Modules\Registration\FEM\include\itkFEMFiniteDifferenceFunctionLoad.hxx(358,3):
error C2039:
'Print': is not a member of 'itk::fem::Solution'
```

and
```
ITK\Modules\Numerics\FEM\include\itkImageToRectilinearFEMObjectFilter.hxx(302,22):
error C2275:
'itk::fem::Material': expected an expression instead of a type
```

```
ITK\Modules\Numerics\FEM\include\itkImageToRectilinearFEMObjectFilter.hxx(302,3):
error C3861:
'itkPrintSelfObject': identifier not found
```

and
```
ITK\Modules\Registration\FEM\include\itkFEMRegistrationFilter.hxx(1471,9):
error C2440:
'static_cast': cannot convert from 'const unsigned int' to 'itk::Size<3>'
```

```
ITK\Modules\Registration\FEM\include\itkFEMRegistrationFilter.hxx(1529,16):
error C2679:
binary '<<': no operator found which takes a right-hand operand of type
'const itk::fem::FEMRegistrationFilter<InputImageType,InputImageType,FEMObjectType>::LandmarkArrayType'
(or there is no acceptable conversion)
```

raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=8462352

Inadvertently introduced in c47ed1c1b3e26051de655f7ad03e975fae93b73b.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
Thank you @jhlegarreta! :green_heart:

**Comment by dzenanz** [comment]
These look like new errors: https://open.cdash.org/viewBuildError.php?buildid=8473470.

**Comment by jhlegarreta** [comment]
> These look like new errors: https://open.cdash.org/viewBuildError.php?buildid=8473470.

Will have a look tonight. The build was passing locally for me on a Win machine with the module at issue enabled. We might want to set up an Azure build with all non-default modules enabled to avoid as much as possible such issues.

**Comment by jhlegarreta** [comment]
> These look like new errors: https://open.cdash.org/viewBuildError.php?buildid=8473470.

Had a look at them. They are the same as those pointed bi Mikhail in here:
https://github.com/InsightSoftwareConsortium/ITK/pull/3872#issuecomment-1424365954

They were addressed as followed in https://github.com/InsightSoftwareConsortium/ITK/pull/3872#issuecomment-1424619519

Not sure why the have been reported to the dashboard.

e.g. the error:
```
M:\Dashboard\ITK\Modules\Registration\FEM\include\itkFEMFiniteDifferenceFunctionLoad.hxx(358,3):
error C2440: 'static_cast':
cannot convert from
'const itk::fem::Solution::ConstPointer' to
'const itk::LightObject *' [M:\Dashboard\ITK-build\Modules\Registration\FEM\test\ITKFEMRegistrationTestDriver.vcxproj]
```

points to this line:
https://github.com/InsightSoftwareConsortium/ITK/pull/3918/files#diff-2f895bbf70bfcc5cf3cbe42cdd153220f8f6570498c24af2117262e39bbdabd2R358

which only contains a string that is being serialized to the ostream.

**Comment by dzenanz** [comment]
For some reason, it used an [old hash](5c97b7605e5bec4e9443b57314b50d4e090a845e) from last week. Info found [here](https://open.cdash.org/viewUpdate.php?buildid=8473470). Let's see whether the error persists tonight.

**Comment by dzenanz** [comment]
I just realized that when `ITK_USE_GPU` is enabled, there are more compile errors coming from PrintSelf PR.

**Comment by jhlegarreta** [comment]
> I just realized that when ITK_USE_GPU is enabled, there are more compile errors coming from PrintSelf PR.

My local set up does not allow me to test that as I do not have OpenCL installed/CMake does not install it when enabling the GPU flag, so if you can set up a machine that enables the flag, I would be able to try to address them.

Thanks.

**Comment by dzenanz** [comment]
Did you give https://github.com/KhronosGroup/OpenCL-SDK/releases a try?

**Comment by dzenanz** [comment]
Here is the log from building on my machine:
[Output-Build.txt](https://github.com/InsightSoftwareConsortium/ITK/files/10745807/Output-Build.txt)

**Comment by jhlegarreta** [comment]
> Did you give https://github.com/KhronosGroup/OpenCL-SDK/releases a try?
I haven't: I do not use the GPU classes/the time/space I have is too limited for this unfortunately.

So PR #3928:
- a06cdd7 fixes the error that stems from a commit of myself where I inadvertently removed the method override:
https://github.com/InsightSoftwareConsortium/ITK/pull/3866/files#diff-951af32ead77aa0eadc6c6647f4f06658391c0956442df3241dfe7d934aa9b6eL148

- b0fdfe8 Commit fixes a compiler error that would arise were the `GPUPDEDeformable` module enabled.

- The errors in `itkGPUFiniteDifferenceImageFilter.hxx` stem from the fact that `itk::TimeProbe` and its parent `itk::ResourceProbe` do not have a Print method. @dzenanz @thewtex were these classes devoid of the printing capability on purpose?

**Comment by dzenanz** [comment]
I assume that lack of `Print` in TimeProbe and ResourceProbe is an oversight.
