### ISSUE TITLE
Cannot set image spacing via SpacingType::Filled

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#3006]
This code snippet does not compile:
```cpp
  using ImageType = itk::Image<short, 3>;
  auto image = ImageType::New();
  image->SetSpacing(ImageType::SpacingType::Filled(0.02));
```
producing this error message:
```text
1>tester.cpp
1>M:\Dev\Tester\tester.cpp(40,57): error C2664: 'void itk::ImageBase<3>::SetSpacing(const itk::Vector<double,3> &)': cannot convert argument 1 from 'itk::FixedArray<T,3>' to 'const itk::Vector<double,3> &'
1>        with
1>        [
1>            T=double
1>        ]
1>M:\Dev\Tester\tester.cpp(40,57): message : Reason: cannot convert from 'itk::FixedArray<T,3>' to 'const itk::Vector<double,3>'
1>        with
1>        [
1>            T=double
1>        ]
1>M:\Dev\Tester\tester.cpp(40,51): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>M:\CDev\ITK-git\Modules\Core\Common\include\itkImageBase.h(422,3): message : see declaration of 'itk::ImageBase<3>::SetSpacing'
```
This is mind boggling.

**Comment by N-Dekker** [comment]
You might just use the `Vector(const ValueType & r)` constructor, which fills the entire vector by the specified element value as well:

    image->SetSpacing(ImageType::SpacingType(0.02));

**Comment by N-Dekker** [comment]
The new (ITK 5.3) way to do this is by calling `itk::MakeFilled<TContainer>`, as follows:

    image->SetSpacing( MakeFilled<ImageType::SpacingType>(0.02) );

`MakeFilled` was introduced by pull request #3247 commit b7715b3e74191624d9a0277fbc8d5126e079b0fe

I think this issue may be closed now.

**Comment by dzenanz** [comment]
I ran into this issue again, but I can now see the workarounds 😉
