### PR TITLE
COMP: Fix `abs` method not being found

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix `abs` method not being found:
- Include `itkMath.h` to have `abs` available.
- Use the standard library `abs` where ITK objects are not used.

Fixes:
```
\Modules\Numerics\FEM\src\itkFEMElement3DC0LinearHexahedron.cxx(223):
error C2039:
'Math': is not a member of 'itk' [M:\Dashboard\ITK-build\Modules\Numerics\FEM\src\ITKFEM.vcxproj]
```

raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=7619926

Introduced in 716822e.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
These went unnoticed because the `FEM`/`FEMRegistration` module(s) is/are not being tested by default.

**Review by hjmjohnson — APPROVED** [review]

**Comment by jhlegarreta** [comment]
The failing `itkPyBufferMemoryLeakTest` test in `ITK.macOS.Python` is unrelated.
