### ISSUE TITLE
ITK does not compile with VS2022 17.7.0

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#4153]
### Steps to Reproduce

Update Visual Studio to:

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.7.0

### Expected behavior

ITK compiles without errors.

### Actual behavior

```log
214>itkPointGTest.cxx
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(369,45): error C2187: syntax error: 'attribute specifier' was unexpected here
214>M:\Dashboard\ITK\Modules\Core\Common\test\itkPointGTest.cxx(63,57): message : see reference to function template instantiation 'auto itk::MakePoint<int,>(const TValue)' being compiled
214>        with
214>        [
214>            TValue=int
214>        ]
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): error C2938: 'itk::MakePoint::<lambda_706d090a84c31981802e12f4e9361bdf>::<lambda_typedef_cdecl>' : Failed to specialize alias template
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): message : see reference to alias template instantiation 'itk::MakePoint::<lambda_706d090a84c31981802e12f4e9361bdf>::<lambda_typedef_cdecl><_T1>' being compiled
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): error C2938: 'itk::MakePoint::<lambda_706d090a84c31981802e12f4e9361bdf>::<lambda_typedef_vectorcall>' : Failed to specialize alias template
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): message : see reference to alias template instantiation 'itk::MakePoint::<lambda_706d090a84c31981802e12f4e9361bdf>::<lambda_typedef_vectorcall><_T1>' being compiled
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): error C2535: 'itk::MakePoint::<lambda_706d090a84c31981802e12f4e9361bdf>::operator unknown-type(void) noexcept const': member function already defined or declared
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): message : see declaration of 'itk::MakePoint::<lambda_706d090a84c31981802e12f4e9361bdf>::operator unknown-type'
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): error C2938: 'itk::MakePoint::<lambda_9e775efe5e487be281683759b49e268a>::<lambda_typedef_cdecl>' : Failed to specialize alias template
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): message : see reference to alias template instantiation 'itk::MakePoint::<lambda_9e775efe5e487be281683759b49e268a>::<lambda_typedef_cdecl><_T1>' being compiled
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): error C2938: 'itk::MakePoint::<lambda_9e775efe5e487be281683759b49e268a>::<lambda_typedef_vectorcall>' : Failed to specialize alias template
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): message : see reference to alias template instantiation 'itk::MakePoint::<lambda_9e775efe5e487be281683759b49e268a>::<lambda_typedef_vectorcall><_T1>' being compiled
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): error C2535: 'itk::MakePoint::<lambda_9e775efe5e487be281683759b49e268a>::operator unknown-type(void) noexcept const': member function already defined or declared
214>M:\Dashboard\ITK\Modules\Core\Common\include\itkPoint.h(367,1): message : see declaration of 'itk::MakePoint::<lambda_9e775efe5e487be281683759b49e268a>::operator unknown-type'
```

### Reproducibility

100%

### Versions

Current master, 336be62d3dab5d4d1f5a7da075298e6de38464e7.

### Environment

Windows 11 x64.

### Additional Information

New version was released two days ago. I updated my local VS yesterday, and last evening had multiple build failures, e.g. [this](https://open.cdash.org/viewBuildError.php?buildid=8899892).

**Comment by N-Dekker** [comment]
Thank for reporting, @dzenanz  I guess it's a brand new compiler bug, but I'll have a closer look.

**Comment by N-Dekker** [comment]
It appears that these compilation errors can be prevented by adding compiler option [/permissive-](https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170). Don't ask why  😸

**Comment by N-Dekker** [comment]
FYI, the following code appears to produce similar error messages:

```
template <typename TValue, typename... TVariadic>
void MyVariadicFunctionTemplate(TValue, TVariadic... otherValues)
{
  auto returnZero = [](auto value) { return 0; };
  int zeros[] = { 0, returnZero(otherValues)... };
}

int main()
{
  MyVariadicFunctionTemplate(42);
}

```

It appears to compile well at https://godbolt.org/z/5reen6qPh but this is what I got locally, from the Developers Command Prompt for VS 2022:

```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.7.0
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************

C:\Program Files\Microsoft Visual Studio\2022\Community>cd /d S:\MyDir

S:\MyDir>cl MyProgram.cpp  /std:c++17 /Bv
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

Compiler Passes:
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x86\cl.exe:        Version 19.37.32822.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x86\c1.dll:        Version 19.37.32822.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x86\c1xx.dll:      Version 19.37.32822.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x86\c2.dll:        Version 19.37.32822.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x86\c1xx.dll:      Version 19.37.32822.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x86\link.exe:      Version 14.37.32822.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x86\mspdb140.dll:  Version 14.37.32822.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x86\1033\clui.dll: Version 19.37.32822.0

MyProgram.cpp
MyProgram.cpp(4): error C2187: syntax error: 'attribute specifier' was unexpected here
MyProgram.cpp(10): note: see reference to function template instantiation 'void MyVariadicFunctionTemplate<int,>(TValue)' being compiled
        with
        [
            TValue=int
        ]
MyProgram.cpp(3): error C2938: 'MyVariadicFunctionTemplate::<lambda_94560b512db532ac0b751669cc94cee2>::<lambda_typedef_cdecl>' : Failed to specialize alias template
MyProgram.cpp(3): note: see reference to alias template instantiation 'MyVariadicFunctionTemplate::<lambda_94560b512db532ac0b751669cc94cee2>::<lambda_typedef_cdecl><_T1>' being compiled
MyProgram.cpp(3): error C2938: 'MyVariadicFunctionTemplate::<lambda_94560b512db532ac0b751669cc94cee2>::<lambda_typedef_stdcall>' : Failed to specialize alias template
MyProgram.cpp(3): note: see reference to alias template instantiation 'MyVariadicFunctionTemplate::<lambda_94560b512db532ac0b751669cc94cee2>::<lambda_typedef_stdcall><_T1>' being compiled
MyProgram.cpp(3): error C2535: 'MyVariadicFunctionTemplate::<lambda_94560b512db532ac0b751669cc94cee2>::operator unknown-type(void) noexcept const': member function already defined or declared
MyProgram.cpp(3): note: see declaration of 'MyVariadicFunctionTemplate::<lambda_94560b512db532ac0b751669cc94cee2>::operator unknown-type'
MyProgram.cpp(3): error C2938: 'MyVariadicFunctionTemplate::<lambda_94560b512db532ac0b751669cc94cee2>::<lambda_typedef_fastcall>' : Failed to specialize alias template
MyProgram.cpp(3): note: see reference to alias template instantiation 'MyVariadicFunctionTemplate::<lambda_94560b512db532ac0b751669cc94cee2>::<lambda_typedef_fastcall><_T1>' being compiled
MyProgram.cpp(3): error C2938: 'MyVariadicFunctionTemplate::<lambda_94560b512db532ac0b751669cc94cee2>::<lambda_typedef_vectorcall>' : Failed to specialize alias template
MyProgram.cpp(3): note: see reference to alias template instantiation 'MyVariadicFunctionTemplate::<lambda_94560b512db532ac0b751669cc94cee2>::<lambda_typedef_vectorcall><_T1>' being compiled

S:\MyDir>
```

**Comment by N-Dekker** [comment]
Reported to Microsoft, please check (and vote for it!): https://developercommunity.visualstudio.com/t/error-C2187-syntax-error:-attribute-sp/10439022

**Comment by N-Dekker** [comment]
@blowekamp Thanks for the update! I still don't understand why these compile errors would be "by design". But anyway, the lambda's that triggered those compile errors are replaced now, so it's no longer an issue at the ITK master branch.

**Comment by blowekamp** [comment]
What this the PR which fixed it: #4154

**Comment by dzenanz** [comment]
Yes.

**Comment by N-Dekker** [comment]
@blowekamp Indeed, PR #4154 commit 89d3c3c0158806ab44a33d3c76b436537864398e avoids the MSVC compile errors. Unfortunately there appeared to be an old Clang compiler that did not like PR #4154. The following PR should also make the old Clang happy:
- #4157

**Comment by N-Dekker** [comment]
Regarding MSVC, I think it was actually a compiler bug, but they just don't want to keep supporting their old C++14/C++17 lambda implementation anymore. They just want us to move forward to use `/std:c++20`, or at least `/Zc:lambda`. But that's just my impression.

**Comment by seanm** [comment]
I've finally had some time to take a look at my ITK cdash submissions, and I bisected this compiler error to 89d3c3c0158806ab44a33d3c76b436537864398e:

https://open.cdash.org/viewBuildError.php?buildid=9059749

```
/Users/builder/external[Modules/Core/Common/include/itkPoint.h:371](https://github.com/InsightSoftwareConsortium/ITK/blob/80446b1c18fde0aaca3eecab6e1e7a30d015ac2c/Modules/Core/Common/include/itkPoint.h#L371):20: error: no viable constructor or deduction guide for deduction of template arguments of 'array'
  const std::array stdArray{ firstValue, otherValues... };
                   ^
[CTest: warning matched] /Users/builder/external[Modules/Core/Common/test/itkPointGTest.cxx:63](https://github.com/InsightSoftwareConsortium/ITK/blob/80446b1c18fde0aaca3eecab6e1e7a30d015ac2c/Modules/Core/Common/test/itkPointGTest.cxx#L63):46: note: in instantiation of function template specialization 'itk::MakePoint<int>' requested here
  static_assert(std::is_same_v<decltype(itk::MakePoint(0))::ValueType, int> &&
                                             ^
[CTest: warning matched] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include[v1/__tuple:223](https://github.com/InsightSoftwareConsortium/ITK/blob/80446b1c18fde0aaca3eecab6e1e7a30d015ac2c/v1/__tuple#L223):64: note: candidate template ignored: could not match 'array<_Tp, _Size>' against 'int'
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
[CTest: warning matched] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include[v1/__tuple:223](https://github.com/InsightSoftwareConsortium/ITK/blob/80446b1c18fde0aaca3eecab6e1e7a30d015ac2c/v1/__tuple#L223):64: note: candidate function template not viable: requires 0 arguments, but 1 was provided
In file included from /Users/builder/external[Modules/Core/Common/test/itkPointGTest.cxx:20](https://github.com/InsightSoftwareConsortium/ITK/blob/80446b1c18fde0aaca3eecab6e1e7a30d015ac2c/Modules/Core/Common/test/itkPointGTest.cxx#L20):
```

This is with the Xcode 10.1 compiler (newest possible on macOS 10.13).

Perhaps there's a formulation that would make both Xcode and MSVC happy?

**Comment by dzenanz** [comment]
I think that formulation is proposed in #4157.

**Comment by seanm** [comment]
Hmmm, I never received the various at-mentions in that other thread... I'll have to figure that out too....

**Comment by seanm** [comment]
Ah ha, I remember now. I was getting so many github emails about ITK that I filtered them into a mailbox I only check occasionally.  I added a new email rule that runs first, to check if `CC` includes `mention@noreply.github.com` and to then make it land in my inbox.  Hopefully I'll now see sooner when you ping me! :)
