### ISSUE TITLE
QuickView.h: No such file or directory

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#5761]
Most likely introduced by #5721.

### Description

The build error [Modules/Bridge/VtkGlue/src/QuickView.cxx:18:10: fatal error: QuickView.h: No such file or directory 18 | #include "QuickView.h"](https://open.cdash.org/viewBuildError.php?buildid=11015522) causes a cascade of build failures.

### Steps to Reproduce

Turn on `Module_ITKVtkGlue`, configure, build.

### Expected behavior

Clean build.

### Actual behavior

Hundreds of tests not run and failing.

### Reproducibility

100%

### Additional Information

Visual Studio editor underlines missing includes:
<img width="306" height="345" alt="Image" src="https://github.com/user-attachments/assets/70bd5089-7547-4e11-982c-5991d5bd4d21" />
When trying to build it outside of dashboard setting, I get: `C:\Dev\ITK-git\Modules\Bridge\VtkGlue\src\QuickView.cxx(18,10): error C1083: Cannot open include file: 'QuickView.h': No such file or directory`
