### PR TITLE
Fail fast for system SWIG 4.4+ with Python limited API

### PR DESCRIPTION
**Pull request by SID-6921**
## Summary
- add a configure-time guard for the known-broken combination:
  - ITK_USE_SYSTEM_SWIG=ON
  - ITK_WRAP_PYTHON=ON
  - ITK_USE_PYTHON_LIMITED_API=ON
  - SWIG_VERSION >= 4.4.0
- emit a clear actionable error instead of allowing a build that fails later at Python import time

## Why
Issue #6479 documents that this combination can compile/link but then fails at import with missing delete_SwigPyIterator from the generated limited-API wrapper module. This change prevents users from reaching that late failure mode.

## User guidance in error
The message recommends one of:
- use system SWIG 4.3.x
- set ITK_USE_PYTHON_LIMITED_API=OFF
- or set ITK_USE_SYSTEM_SWIG=OFF

## Testing
- CMake configure logic change only (no runtime behavior change outside guarded configuration path)
- patch validated by source inspection and targeted diff.

### CODE REVIEW

**Comment by SID-6921** [comment]
Applied the wording nit from review: updated the in-file note to say SWIG 4.4+ (matching the VERSION_GREATER_EQUAL 4.4.0 guard) in commit 4b11d44092.

**Review by thewtex — APPROVED** [review]
@SID-6921 thanks for the contribution! 🙏

**Comment by dzenanz** [comment]
Preferably squash upon merge.

**Comment by dzenanz** [comment]
Or even better, squash into one commit now.

**Comment by SID-6921** [comment]
Done. I squashed the branch into a single commit as requested and force-pushed: 3eccfe7203.

**Review by dzenanz — APPROVED** [review]

**Review by hjmjohnson — CHANGES_REQUESTED** [review]
Thanks for the PR, but this guard blocks a configuration that now works. The failure described in #6479 was fixed by #6484 (merged 2026-06-23), which moved ITK's Python wrapping to SWIG 4.4.1 and added a runtime shim for SWIG 4.4's PEP 489 multi-phase init.

<details>
<summary>Details</summary>

- SWIG 4.4 makes `PyInit_*` return a raw `PyModuleDef`; ITK's injected module-packing code previously stored that directly in `sys.modules`, producing the `'moduledef' object has no attribute 'delete_SwigPyIterator'` import failure.
- #6484 added detection of the returned def and instantiation via `PyModule_FromDefAndSpec` + `PyModule_ExecDef` (`Wrapping/Generators/Python/CMakeLists.txt`). The shim lives in ITK's generated glue, so it applies equally to system and vendored SWIG.
- The vendored SWIG is now itself 4.4.1, so CI exercises SWIG 4.4.1 + Limited API on every run — the exact combination this guard rejects.
- #6479 stayed open only because the fixing PR's body didn't use a GitHub auto-close keyword; it is now closed as fixed.

</details>

This PR should be closed as obsolete — on current `main` there is no broken combination to guard against, and the existing `swig_version_min` check already handles too-old system SWIG.

**Comment by hjmjohnson** [comment]
@SID-6921 I think you probably built this PR on an intermediate ITKv6  codebase.  This has been fixed in the main branch.  See detailed analysis https://github.com/InsightSoftwareConsortium/ITK/pull/6544#pullrequestreview-4629737650.  

Thank you for the contribution!  Keep suggestions coming!
