### PR TITLE
BUG: Fix variable typo `MultiphaseDenseFiniteDifferenceImageFilter` test

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix variable spelling mistake in `Review` module
`itk::MultiphaseDenseFiniteDifferenceImageFilter` class test file.

Fixes:
```
/Nonunit/Review/test/itkMultiphaseDenseFiniteDifferenceImageFilterTest.cxx:115:47:
error: use of undeclared identifier 'flter'; did you mean 'filter'?
  ITK_TEST_SET_GET_VALUE(reinitializeCounter, flter->GetReinitializeCounter());
                                              ^~~~~
                                              filter
```

introduced in commit 669a39c.

Raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=8135692

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
My mistake.

**Review by N-Dekker — APPROVED** [review]
Thanks Jon! You might have made the subject line somewhat more specific (as long as it is <= 72 characters, of course) for example:

    BUG: Fix variable typo MultiphaseDenseFiniteDifferenceImageFilter test

But approved anyway, Looks fine to me!  👍
