### ISSUE TITLE
itk python 5.3rc3 -- error importing python methods

### ISSUE THREAD

**Issue by wyli** [InsightSoftwareConsortium/ITK#3137]
### Description

some importing commands don't work in 5.3rc3

### Steps to Reproduce

```bash
pip install itk==5.3rc3
python -c "import itk; itk.WarpImageFilter"
```

### Expected behavior

no error

### Actual behavior

```py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/anaconda3/envs/py37/lib/python3.7/site-packages/itk/support/lazy.py", line 130, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'itk' has no attribute 'WarpImageFilter'
```

### Versions

itk-5.3rc3

### Environment

evaluated with macOS and ubuntu

**Comment by wyli** [comment]
looks like it's an issue only if a previous version is installed already:
```bash
pip install itk==5.3rc2; 
pip install itk==5.3rc3; 
python -c "import itk; itk.WarpImageFilter"
```

the problem can be fixed by simply reinstalling with 
```bash
pip install --force-reinstall itk==5.3rc3
```
I guess it's not a critical issue I'm closing this ticket.

**Comment by thewtex** [comment]
@wyli thanks for the update!
