### PR TITLE
COMP: Remove spare closing bracket

### PR DESCRIPTION
**Pull request by jhlegarreta**
Remove spare closing bracket.

Left behind inadvertently in commit 2bd9f0a.

Fixes:
```
T:\Dashboard\ITK\Modules\Filtering\GPUAnisotropicSmoothing\include\itkGPUAnisotropicDiffusionImageFilter.hxx(66,76):
 error C2187: syntax error: ')' was unexpected here
 [T:\Dashboard\ITK-build\Modules\Filtering\GPUAnisotropicSmoothing\ITKGPUAnisotropicSmoothingHeaderTest1.vcxproj]
```

raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=10232159

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Have not tried to build locally.

**Review by dzenanz — APPROVED** [review]

**Review by N-Dekker — APPROVED** [review]
Thanks Jon! I see, my fault, sorry! 🤷 

- For the record, the flaw was introduced by pull request #5252 commit 2bd9f0a31a8d08234447db45d87910d7d6a7b135
