### PR TITLE
zlib-ng 2022-04-27 (d41f8ead)

### PR DESCRIPTION
**Pull request by dzenanz**
Code extracted from:

    https://github.com/zlib-ng/zlib-ng.git

at commit d41f8ead569ee805b323b45fca30430cefe91cfd (develop).

### CODE REVIEW

**Comment by dzenanz** [comment]
It has some trailing whitespace, but I would like to check CI first.

**Comment by dzenanz** [comment]
Trailing whitespace was fixed upstream: https://github.com/zlib-ng/zlib-ng/pull/1257.

**Comment by tbirdso** [comment]
@dzenanz Could you add a few details on the motivation for this PR? And, am I understanding correctly that all changes are copied/pasted as-is from the upstream commit in the PR description? Trying to understand how closely to review this (large) PR, if it is already well tested upstream I imagine there is less need to pick through all of the details.

**Comment by dzenanz** [comment]
This is an automated update from upstream. Only a cursory review is expected.

**Review by tbirdso — APPROVED** [review]

**Comment by seanm** [comment]
This seems to have broken the build on macOS 10.11 with AppleClang 8:

```
/Users/builder/external/ITK/Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/x86/adler32_avx2.c:55:13: error: initializing '__m256i' (vector of 4 'long long' values) with an expression
      of incompatible type 'int'
    __m256i vs1 = _mm256_zextsi128_si256(_mm_cvtsi32_si128(adler));
            ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/external/ITK/Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/x86/adler32_avx2.c:56:13: error: initializing '__m256i' (vector of 4 'long long' values) with an expression
      of incompatible type 'int'
    __m256i vs2 = _mm256_zextsi128_si256(_mm_cvtsi32_si128(sum2));
            ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

See: https://open.cdash.org/viewBuildError.php?buildid=7889929

**Comment by seanm** [comment]
Created upstream ticket: https://github.com/zlib-ng/zlib-ng/issues/1264

**Comment by seanm** [comment]
@dzenanz I've got a fix merged upstream. @dzenanz could you update ITK?

**Comment by tbirdso** [comment]
I believe @dzenanz is out for a couple of days, perhaps @thewtex could help?

**Comment by thewtex** [comment]
I bumped the version here:

  https://github.com/InsightSoftwareConsortium/ITK/pull/3422

Note that this can be created by running:

```
  ./Modules/ThirdParty/ZLIB/UpdateFromUpstream.sh  
```
