### ISSUE TITLE
`DCMTK` `IO` module does not compile on Windows

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITK#2817]
### Description

The `DCMTK` `IO` module does not compile.

### Steps to Reproduce

1. Configure ITK with the `Module_ITKIODCMTK:BOOL=ON`; `DCMTK_USE_ICU=OFF`
2. Build ITK
3. ITK will fail to compile with the following message
```
/Modules/IO/DCMTK/include/itkDCMTKFileReader.h(27,10): fatal error C1083:
Cannot open include file: 'dcmtk/dcmdata/dcdict.h': No such file or directory
```

The file, however, does exist in the build tree:
```
/itk-head-Bin/Modules/ThirdParty/DCMTK/ITKDCMTK_ExtProject/dcmdata/include/dcmtk/dcmdata/dcdict.h
```

### Expected behavior

ITK should build with no errors.

### Actual behavior

It does not build.

### Reproducibility

100%.

### Versions

ITK `master`.

### Environment

OS: Windows 10
CMake: 3.20.3
Compiler: MSVC 2019 19.29.30133.0
Build: static; debug

### Additional Information

Reproduced/confirmed by @dzenanz in https://github.com/InsightSoftwareConsortium/ITK/pull/2796#issuecomment-940259623.

The `DCMTK` module compiles fine as stand-alone project for the [tag used in `ITK`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/DCMTK/DCMTKGitTag.cmake#L22), but linking to it as a system module (`ITK_USE_SYSTEM_DCMTK`) in CMake results also in another type of errors:
```
LINK : fatal error LNK1104: cannot open file 'ofstd.lib'
```

The file, however, does exist in the DCMTK build tree:
```
/dcmtk-Bin/lib/Debug
```

Related to PR #2796.

The warnings cast when building `DCMTK` were reported in #2798.

The module seems to compile fine on `Linux`:
https://open.cdash.org/build/7512875/notes
https://open.cdash.org/build/7512875

**Comment by jhlegarreta** [comment]
This is still relevant stale bot.

**Comment by jhlegarreta** [comment]
@tbirdso @dzenanz I'd be grateful if, at some point, you would be able to spend some time to look into this issue and hopefully fix it. If it were fixed, I could give #2796 a try, see if I can wrap that up. It could get us back to the 90% coverage level. Thanks both for your time and effort.

**Comment by tbirdso** [comment]
Hi @jhlegarreta, I won't be able to help this week but can take a look in the not-too-far future. I am not very familiar with the DCMTK CMake code in ITK. Given that the failure is only on Windows, maybe there is a path length issue somewhere?

**Comment by jhlegarreta** [comment]
>  won't be able to help this week but can take a look in the not-too-far future.

No worries. It is not urgent, but nice to fix at some point.

> I am not very familiar with the DCMTK CMake code in ITK. Given that the failure is only on Windows, maybe there is a path length issue somewhere?

Not sure about the underlying causes.

**Comment by dzenanz** [comment]
Also possibly related: #2872.

**Comment by tbirdso** [comment]
@jhlegarreta I was not able to immediately recreate this issue. The `ITKIODCMTKTestDriver` target appears to compile on first try on my Windows machine. I have double checked that `Module_ITKIODCMTK=ON` and `DCMTK_USE_ICU=ON` in my CMake configuration. 

Could you please confirm whether you are still seeing this issue when you try building? If so, could you please try upgrading your CMake version and/or changing your build type to see if that helps?

Platform: Windows 10
CMake: 3.22.3
Compiler: MSVC 2022 14.31.31103
Build type: RelWithDebInfo

**Comment by jhlegarreta** [comment]
I submitted an experimental build to
https://open.cdash.org/viewBuildError.php?buildid=7989296

My toolchain is the following:
Platform: Windows 10
CMake 3.20.2
Compiler: MSVC 2019 (Microsoft Visual Studio Community 2019 Version 16.11.7)
Build type: Debug

(So "reasonably up-to-date" I'd dare to say)

Note that there are additional build errors due to some local, unfinished additions (sorry for the noise they add), but you can see that the `IODCMTK` module is not compiling.

I did not check the `DCTMK_USE_ICU` CMake flag because the CMake configuration step failed when I checked it: contrary to what that is supposed to do (intuitively, and as its help says - `Downloads and compile ICU for DCMTK`), it resulted in the following CMake error:
```
CMake Error at Modules/ThirdParty/DCMTK/CMakeLists.txt:17 (message):
ICU is not built as part of ITK on Windows. Please compile it outside of
ITK.
```

And I was not willing to download and compile ICU in case it resulted in new issues.

In fact, I think that is a separate issue, though, as the build errors point rather to issue #2872

**Comment by tbirdso** [comment]
@jhlegarreta I agree that this is a separate issue. The original error message
```
LINK : fatal error LNK1104: cannot open file 'ofstd.lib'
```
does not appear to be present in the build you posted, and as you pointed out the new errors
```
error LNK2038: mismatch detected for 'RuntimeLibrary':
```
could indeed be explained by issue #2872.

It does not appear that we are able to reproduce this issue, I am in favor of closing it. @jhlegarreta @dzenanz do you agree?

**Comment by jhlegarreta** [comment]
The error
```
LINK : fatal error LNK1104: cannot open file 'ofstd.lib
```

appears when using a system `DCTK`.

Thus, there are multiple errors, from different nature, with the module, and thus I think the issue is still applicable and different from #2872. Note that the above error was reproduced by @dzenanz, as commented in the original issue report.

Note that this error appeared as I tried to use a system `DCMTK` because the remote module build was failing. I grant that the remote was originally failing with a different error (see the original issue report):
```
/Modules/IO/DCMTK/include/itkDCMTKFileReader.h(27,10): fatal error C1083:
Cannot open include file: 'dcmtk/dcmdata/dcdict.h': No such file or directory
```

but even if in the experimental build it does not seem to be present, I should double check with a regular build.

So I am not quite in favor of closing the issue.

**Comment by jhlegarreta** [comment]
> But even if in the experimental build it does not seem to be present, I should double check with a regular build.

Not present either in a regular build. So it somehow looks that that one is gone now, and it's the compiler flag errors that persist.

**Comment by thewtex** [comment]
We may want to see what Slicer is doing in their build for Windows.

**Comment by issakomi** [comment]
Didn't fail here too: https://open.cdash.org/build/8268393

**Comment by jhlegarreta** [comment]
Thanks for the information @issakomi. I had tried compiling a few days ago without success, and the same error being reported. Now I've tried again this afternoon with a clean build and it looks like things are OK. I need to have a closer look. I will follow up with this as time permits.

**Comment by jcfr** [comment]
> We may want to see what Slicer is doing in their build for Windows.

Ditto. Thanks to @jamesobutler who started to work on updating DCMTK in Slicer, we will be working on this.

**Comment by jhlegarreta** [comment]
I gave this another try with a new, clean target folder and reduced the scope of the error to the test, but did not find a solution.

In summary, `DCMTK` `IO` module DOES compile on Windows (Win 10, CMake 3.24.2, MSVC 2022; having enabled both `ITKDCMTK` and `ITKIODCMTK` modules enabled; with and without testing enabled). But the test in #2796 does not compile due to a missing header file.

So I'm closing this issue in favor of #3820, which has a more faithful report of the problem.
