### PR TITLE
COMP: Fix older gcc build error including "cstddef" for "ptrdiff_t"

### PR DESCRIPTION
**Pull request by jcfr**
This commit fixes a regression likely introduced in c173dfd80 (STYLE: Remove `std::` prefix from types that work without it) to support building ITK wheels using manylinux_2_24 providing gcc 6.3.

It fixes build error like the following:

```
  In file included from /work/ITK-source/ITK/Modules/Core/Common/include/itkImageRegion.h:33:0,
                   from /work/ITK-source/ITK/Modules/Core/Common/include/itkMultiThreaderBase.h:35,
                   from /work/ITK-source/ITK/Modules/Core/Common/src/itkTotalProgressReporter.cxx:19:
  /work/ITK-source/ITK/Modules/Core/Common/include/itkSize.h:242:27: error: ‘ptrdiff_t’ does not name a type
     using difference_type = ptrdiff_t;
                             ^~~~~~~~~
```

cc: @Leengit 

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by thewtex** [comment]
Addressed clang-format issues locally (the applyClangFormat label / action has permissions issue).

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
:+1: thanks jcfr :pray:

**Comment by jcfr** [comment]
Thanks @thewtex for the follow up :100:

**Comment by thewtex** [comment]
\azp run ITK.macOS

**Review by hjmjohnson — APPROVED** [review]
