### PR TITLE
ENH: Add itk.__version__

### PR DESCRIPTION
**Pull request by thewtex**
This is a standard attribute used to provide the version in Python
packages.

Co-authored-by: Matthew Rocklin <mrocklin@gmail.com>

### CODE REVIEW

**Comment by thewtex** [comment]
@mrocklin

File: Wrapping/Generators/Python/itk/__init__.py.in [hunk 1]
```diff
@@ -25,6 +25,7 @@
 import os
 import sys
 
+__version__ = "@ITK_VERSION_MAJOR@.@ITK_VERSION_MINOR@.@ITK_VERSION_PATCH@"
```
Comment (dzenanz) [inline Wrapping/Generators/Python/itk/__init__.py.in]: Is `PythonSuffix` available here? Should it go into this version string?

Comment (thewtex) [reply Wrapping/Generators/Python/itk/__init__.py.in]: Unfortunately, the suffix is not available here.

**Comment by thewtex** [comment]
Failing test is unrelated.

**Comment by function2-llx** [comment]
Hi, I'm using itk 5.1.2, running `python -c "import itk; itk.__version__"` still raises `AttributeError: module 'itk' has no attribute '__version__'`.

**Comment by Leengit** [comment]
It works with itk==5.2.0, which is available, though the official release is not yet out.

**Comment by function2-llx** [comment]
@Leengit Got it, thanks.
