### PR TITLE
COMP: Expose itkeigen subdir in ITKEigen3_INCLUDE_DIRS for external consumers

### PR DESCRIPTION
**Pull request by hjmjohnson**
Add `${ITKEigen3_SOURCE_DIR}/src/itkeigen` to `ITKEigen3_INCLUDE_DIRS` so external consumers using the upstream Eigen include convention (`<Eigen/<header>>`) resolve against the vendored Eigen via ITK's IMPORTED targets — currently they get `fatal error: Eigen/Dense: No such file or directory`. Unblocks InsightSoftwareConsortium/ITKTotalVariation # 57's modern-target-interfaces refactor for proxTV. **Independent of and complementary to #6176** (the Eigen 5 update); the architecture issue predates that PR.

<details>
<summary>Root cause</summary>

ITK ships its vendored Eigen3 headers at:
```
Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/<header>
```

ITK's own internal code uses `ITK_EIGEN(<header>)` from `itk_eigen.h`, which expands to `<itkeigen/Eigen/<header>>`. With include path `${ITKEigen3_SOURCE_DIR}/src` (the parent of `itkeigen/`), the compiler appends `/itkeigen/Eigen/<header>` and resolves correctly. ITK proper has always built fine.

`Modules/ThirdParty/Eigen3/CMakeLists.txt:58` (vendored case, before this PR):
```cmake
set(ITKEigen3_INCLUDE_DIRS ${ITKEigen3_SOURCE_DIR}/src)
```

That single path flowed into `INTERFACE_INCLUDE_DIRECTORIES` of both `ITK::ITKEigen3Module` and `ITK::eigen_internal`. External consumers using the upstream `<Eigen/<header>>` convention got the wrong root and failed to resolve. The `Eigen3::Eigen` IMPORTED target produced by Eigen's own export does have the correct path, but it's declared as `add_library(Eigen3::Eigen ALIAS eigen)` — an in-source-scope alias, invisible to FetchContent sub-builds (verified empirically).

</details>

<details>
<summary>Fix</summary>

Single-block change to `Modules/ThirdParty/Eigen3/CMakeLists.txt:58`:
```diff
-  set(ITKEigen3_INCLUDE_DIRS ${ITKEigen3_SOURCE_DIR}/src)
+  set(
+    ITKEigen3_INCLUDE_DIRS
+    ${ITKEigen3_SOURCE_DIR}/src
+    ${ITKEigen3_SOURCE_DIR}/src/itkeigen
+  )
```

ITK's own `<itkeigen/Eigen/<header>>` consumers continue to find their headers via the first entry. External consumers using `<Eigen/<header>>` find theirs via the second. Both flow into `INTERFACE_INCLUDE_DIRECTORIES` of the IMPORTED `ITK::ITKEigen3Module` so the fix applies in-tree and to `find_package(ITK)` consumers identically.

</details>

<details>
<summary>Local verification</summary>

Full ITK build with `Module_TotalVariation=ON` pinned at ITKTotalVariation # 57's tip (`39e849e`, which previously failed `lapackFunctionsWrap.cpp:11:10: fatal error: Eigen/Dense: No such file or directory`):

| Step | Result |
|---|---|
| Configure (`ITK_BUILD_DEFAULT_MODULES=ON`, Module_TotalVariation pinned at PR # 57 tip) | ✅ clean |
| Build `ninja -j16` | ✅ **6165/6165** targets, 0 failures |
| `libitkproxTV-6.0.so` produced | ✅ |
| `bin/TotalVariationTestDriver` linked | ✅ |
| `ctest -R ProxTV` | ✅ `itkProxTVImageFilterTest` passes |
| `lapackFunctionsWrap.cpp.o` compile flags include `-isystem .../Eigen3/src/itkeigen` | ✅ (the vendored path resolves `<Eigen/Dense>`) |
| Compile flags do **not** include `-isystem /usr/include/eigen3` | ✅ (no longer falling back to system Eigen) |

Compile-commands receipt for `lapackFunctionsWrap.cpp`:
```
-I/tmp/itk-eigen-include-fix-build/_deps/proxtv_fetch-src/src
-I.../Eigen3/src
-I.../build/Modules/ThirdParty/Eigen3/src
-isystem .../Eigen3/src/itkeigen        ← the new include dir from this PR
```

</details>

<details>
<summary>Relationship to other PRs</summary>

- **#6176** (Eigen 5 vendored update) — independent. The architecture issue this PR fixes predates the Eigen 5 update; `upstream/main` has the same setup. PR #6176 is good to merge as-is. After both this PR and #6176 land, no further coordination is needed.
- **InsightSoftwareConsortium/ITKTotalVariation# 57** (cmake_interface_update) — unblocked by this PR. Their `set(proxTV_Eigen_LIBRARIES ITK::ITKEigen3Module)` becomes correct as-is, no further changes needed in TotalVariation. The longstanding "silent fall-through to system Eigen" bug in ITKTotalVariation `main` (where `set(Eigen3_DIR "${ITKInternalEigen3_DIR}")` reads an empty value) becomes moot once # 57 lands, because proxTV no longer needs the broken `Eigen3_DIR` shim.

</details>

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

File: Modules/ThirdParty/Eigen3/CMakeLists.txt [hunk 1]
```diff
@@ -55,7 +55,18 @@ if(ITK_USE_SYSTEM_EIGEN)
...
+  # Eigen convention <Eigen/X> resolve.  ITK code rooted at
+  # ${ITKEigen3_SOURCE_DIR}/src uses the macro form; external
+  # consumers (proxTV, anything else that includes Eigen the
+  # standard way) need the parent of <Eigen/X>, which is
+  # ${ITKEigen3_SOURCE_DIR}/src/itkeigen.
+  set(
+    ITKEigen3_INCLUDE_DIRS
+    ${ITKEigen3_SOURCE_DIR}/src
+    ${ITKEigen3_SOURCE_DIR}/src/itkeigen
+  )
```
[the remark this answers is not in the document]
Comment (hjmjohnson) [reply Modules/ThirdParty/Eigen3/CMakeLists.txt:69]: Investigating.

[the remark this answers is not in the document]
Comment (hjmjohnson) [reply Modules/ThirdParty/Eigen3/CMakeLists.txt:69]: Concern is valid in principle but the recommended drop-in does not work — surfaces a separate ITK macro-plumbing bug. Closing as discussed; tracking the cleanup as a follow-up.

**What the trivial swap does**

Replacing `set(ITKEigen3_INCLUDE_DIRS ... ${ITKEigen3_SOURCE_DIR}/src/itkeigen)` with `set(ITKEigen3_SYSTEM_INCLUDE_DIRS ${ITKEigen3_SOURCE_DIR}/src/itkeigen)` (otherwise identical) fails the CMake **generate** step:

```
CMake Error in Modules/ThirdParty/Eigen3/CMakeLists.txt:
  Target "ITKEigen3Module" INTERFACE_INCLUDE_DIRECTORIES property contains path: ...
```

Root cause sits in `CMake/ITKModuleMacros.cmake:264-289`. The regular-include loop wraps each path in `$<BUILD_INTERFACE:...>`:

```cmake
foreach(_dir ${${itk-module}_INCLUDE_DIRS})
  list(APPEND ${itk-module}_GENEX_INCLUDE_DIRS "$<BUILD_INTERFACE:${_dir}>")
endforeach()
```

The SYSTEM-include loop does **not** — paths are added raw:

```cmake
if(${itk-module}_SYSTEM_INCLUDE_DIRS)
  foreach(_dir ${${itk-module}_SYSTEM_INCLUDE_DIRS})
    list(APPEND ${itk-module}_SYSTEM_GENEX_INCLUDE_DIRS ${_dir})
  endforeach()
endif()
```

The documented design intent at line 273-274 of the same file: *"System include directories are assumed to be external dependencies that are not installed, and thus do not have separate install interface paths."* `_SYSTEM_INCLUDE_DIRS` is structurally for `/usr/include`-style paths, not in-source paths that need install-interface separation. Putting an in-tree absolute path there causes CMake to reject the resulting `INTERFACE_INCLUDE_DIRECTORIES` at export time.

**What it would take to do this properly**

Three paths, all larger than this PR:

1. Extend the SYSTEM-include loop in `ITKModuleMacros.cmake` to also wrap in `$<BUILD_INTERFACE:>` / `$<INSTALL_INTERFACE:>`. Need to audit every existing `_SYSTEM_INCLUDE_DIRS` consumer in the tree to confirm none of them depend on the raw-path behavior. Touches the module macro that every ITK module uses.

2. Add `target_include_directories(eigen_internal SYSTEM INTERFACE $<BUILD_INTERFACE:${ITKEigen3_SOURCE_DIR}/src/itkeigen>)` directly inside `Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt`, mirroring the existing `${CMAKE_CURRENT_SOURCE_DIR}` line there. Bypasses the broken macro path. Smaller surface but only addresses the new path; still leaves `${ITKEigen3_SOURCE_DIR}/src` (the long-standing `<itkeigen/Eigen/X>` ITK-internal convention path) as a regular include for symmetry — same warning-leakage concern, just for a different consumer set.

3. Move both `${ITKEigen3_SOURCE_DIR}/src` AND the new `/itkeigen` path to SYSTEM. Symmetry argument is correct (both paths root at the same Eigen template instantiation site, both leak the same `-Wshadow`/`-Wmaybe-uninitialized`/etc. on consumers). But this *changes* the warning surface for every existing in-tree consumer of `ITK::ITKEigen3Module` that currently builds clean with `-I .../src` regular — non-trivial CI risk.

**Decision for this PR**

Keep the regular `_INCLUDE_DIRS` form. The PR's stated goal is to unblock proxTV / ITKTotalVariation#57's `<Eigen/Dense>` resolution; that's a P0 blocker and this fix achieves it minimally. The warning-suppression cleanup is a P2 quality concern that requires either macro-plumbing surgery or a tree-wide warning-surface audit; either is wider scope than the unblock and deserves a dedicated follow-up PR with proper CI verification.

Will open a tracking issue for the SYSTEM-include cleanup so it doesn't fall through.

Resolving this thread.

**Comment by hjmjohnson** [comment]
Tracking issue for the SYSTEM-include macro cleanup is now open: #6224 — captures the macro-plumbing diagnosis, the three approaches in increasing scope, and the recommended sequencing (investigate the existing `eigen_internal SYSTEM INTERFACE` first; only touch `ITKModuleMacros.cmake` if needed).

File: Modules/ThirdParty/Eigen3/CMakeLists.txt [hunk 2]
```diff
@@ -55,7 +55,18 @@ if(ITK_USE_SYSTEM_EIGEN)
...
 else()
   set(ITKEigen3_LIBRARIES eigen_internal)
-  set(ITKEigen3_INCLUDE_DIRS ${ITKEigen3_SOURCE_DIR}/src)
+  # Two include directories are required so both ITK's own
+  # ITK_EIGEN(X) macro convention <itkeigen/Eigen/X> and the upstream
+  # Eigen convention <Eigen/X> resolve.  ITK code rooted at
+  # ${ITKEigen3_SOURCE_DIR}/src uses the macro form; external
+  # consumers (proxTV, anything else that includes Eigen the
+  # standard way) need the parent of <Eigen/X>, which is
+  # ${ITKEigen3_SOURCE_DIR}/src/itkeigen.
```
Comment (blowekamp) [inline Modules/ThirdParty/Eigen3/CMakeLists.txt:64]: This comment is too long, and not efficient for humans to understand.

**Comment by blowekamp** [comment]
PR #57 was not blocked because of a compilation error it was blocked because of incompatible ITK versioning infrastructure.

**Comment by seanm** [comment]
I haven't bisected yet, but looking at what changed in ITK since yesterday, I suspect this change broke my build:

```
In file included from /some/path/ITK-install/include/ITK/itkAffineTransform.h:21:
In file included from /some/path/ITK-install/include/ITK/itkMatrixOffsetTransformBase.h:24:
In file included from /some/path/ITK-install/include/ITK/itkTransform.h:24:
In file included from /some/path/ITK-install/include/ITK/itkSymmetricSecondRankTensor.h:29:
/some/path/ITK-install/include/ITK/itkSymmetricEigenAnalysis.h:23:10: fatal error: 'itkeigen/Eigen/Eigenvalues' file not found
#include ITK_EIGEN(Eigenvalues)
         ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by seanm** [comment]
Bisect results:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
bc87d16685adbadd975a619beef26a030a53b922
64ddc6660c82966f47cbf36ef25175a8792c7df0
We cannot bisect more!

**Comment by seanm** [comment]
So in fact it was MR https://github.com/InsightSoftwareConsortium/ITK/pull/6176  I'll move comments there...
